"""Content for SQL Frog Worlds 2-7 plus the final Grand Trial — continues
directly from World 1 (levels.py): the pond's frogs have grown up and moved
into named ponds across the village, which is exactly the two-table
(`frogs` + `ponds`) shape World 3 onward needs for joins/subqueries/CTEs/
window functions. World 2 stays on World 1's original single `frogs` table
since aggregates don't need a second table yet.

Every `expected_result` below was generated by actually executing the
level's answer query against real sqlite3 with this exact schema/seed (see
the one-off generator script used to build this file) — never hand-typed —
same non-negotiable rule as World 1. Two deliberate constraints carried
through every level here because of how grading works (see
views/_shared.py's _parse_sql_frog_stdout/_sql_frog_grade docstrings, which
can't be verified against Judge0's actual SQLite from this dev environment):
no graded level's expected output may contain a literal NULL cell (LAG's
boundary row uses its 3-argument default instead of leaving one), and every
AVG is wrapped in ROUND(..., 2) with the mission text saying so, since the
grader compares numbers by exact value, not with tolerance.
"""

from .levels import FROGS_SCHEMA, FROGS_SEED

VILLAGE_SCHEMA = """
CREATE TABLE frogs (
  id INTEGER PRIMARY KEY,
  name TEXT,
  color TEXT,
  weight_kg REAL,
  score INTEGER,
  team TEXT,
  pond_id INTEGER
);
CREATE TABLE ponds (
  id INTEGER PRIMARY KEY,
  name TEXT,
  climate TEXT,
  max_capacity INTEGER
);
"""

VILLAGE_SEED = """
INSERT INTO ponds (name, climate, max_capacity) VALUES
('Willow Pond', 'temperate', 50),
('Frost Pond', 'cold', 20),
('Mangrove Pond', 'tropical', 80),
('Desert Oasis', 'arid', 10);

INSERT INTO frogs (name, color, weight_kg, score, team, pond_id) VALUES
('Kermit', 'green', 8.5, 92, 'Leap', 1),
('Pepe', 'green', 6.0, 75, 'Splash', 1),
('Rana', 'green', 9.9, 60, 'Croak', 2),
('Michigan', 'brown', 12.0, 55, 'Croak', 2),
('Toady', 'brown', 15.5, 40, 'Hop', NULL),
('Ribbit', 'blue', 7.2, 88, 'Leap', 3),
('Splash', 'blue', 5.5, 95, 'Splash', 1),
('Hoppy', 'red', 11.0, 70, 'Hop', 3),
('Bullfrog', 'red', 20.0, 30, 'Croak', 2),
('Lily', 'yellow', 4.5, 82, 'Splash', NULL),
('Krok', 'green', 13.3, 65, 'Hop', 3),
('Marsh', 'blue', 9.0, 78, 'Leap', 1);
"""

VILLAGE_SCHEMA_INFO = {
    "table": "frogs + ponds",
    "columns": ["frogs: id, name, color, weight_kg, score, team, pond_id", "ponds: id, name, climate, max_capacity"],
    "sample_rows": [
        ["frogs", 1, "Kermit", "green", 8.5, 92, "Leap", 1],
        ["ponds", 1, "Willow Pond", "temperate", 50],
    ],
}


def _village_schema_view(extra_note=""):
    """The reference panel needs real sample rows from BOTH tables, not the
    single-table shape SchemaPanel/SqlFrogLevelDetailView was built for —
    this returns two panels' worth of data the view assembles into a list."""
    return [
        {
            "table": "frogs",
            "columns": ["id", "name", "color", "weight_kg", "score", "team", "pond_id"],
            "sample_rows": [
                [1, "Kermit", "green", 8.5, 92, "Leap", 1],
                [5, "Toady", "brown", 15.5, 40, "Hop", None],
            ],
        },
        {
            "table": "ponds",
            "columns": ["id", "name", "climate", "max_capacity"],
            "sample_rows": [
                [1, "Willow Pond", "temperate", 50],
                [4, "Desert Oasis", "arid", 10],
            ],
        },
    ]


WORLD_2_LEVELS = [
    {
        "id": "w2_l01", "order": 15, "world": 2,
        "title": "Counting the Village",
        "story": "The frogs have grown up and spread across the village's ponds. The mayor wants a census: how many frogs live here in total?",
        "concept_title": "COUNT — How Many Rows?",
        "concept_explanation": "COUNT(*) counts how many rows match — one number back, no matter how many columns the table has.",
        "example": {"query": "SELECT COUNT(*) FROM pond_visitors;", "columns": ["COUNT(*)"], "result": [[2]]},
        "mission": "Count every frog in the village.",
        "schema_sql": FROGS_SCHEMA, "seed_sql": FROGS_SEED,
        "expected_result": [[12]],
        "order_matters": False,
        "hints": [
            "You want one number: the total number of frogs.",
            "COUNT(*) counts every row in a table.",
            "SELECT COUNT(*) FROM frogs;",
        ],
        "xp_reward": 150, "coin_reward": 35, "skill_unlocked": "COUNT",
    },
    {
        "id": "w2_l02", "order": 16, "world": 2,
        "title": "The Village Scale",
        "story": "A giant scale at the village gate can weigh the whole population at once — if you ask it the right way.",
        "concept_title": "SUM — Add a Column Up",
        "concept_explanation": "SUM(column) adds up every value in that column across all matching rows.",
        "example": {"query": "SELECT SUM(id) FROM pond_visitors;", "columns": ["SUM(id)"], "result": [[3]]},
        "mission": "Find the combined weight of every frog in the village.",
        "schema_sql": FROGS_SCHEMA, "seed_sql": FROGS_SEED,
        "expected_result": [[122.4]],
        "order_matters": False,
        "hints": [
            "You need to add up the weight_kg column.",
            "SUM(column) totals a numeric column.",
            "SELECT SUM(weight_kg) FROM frogs;",
        ],
        "xp_reward": 150, "coin_reward": 35, "skill_unlocked": "SUM",
    },
    {
        "id": "w2_l03", "order": 17, "world": 2,
        "title": "The Report Card",
        "story": "The village school wants to know how the frogs are doing on average this term.",
        "concept_title": "AVG — The Average",
        "concept_explanation": "AVG(column) computes the mean of a numeric column. Since it can produce long decimals, wrap it in ROUND(AVG(column), 2) to keep it to 2 decimal places.",
        "example": {"query": "SELECT ROUND(AVG(id), 2) FROM pond_visitors;", "columns": ["ROUND(AVG(id), 2)"], "result": [[1.5]]},
        "mission": "Find the average score of every frog, rounded to 2 decimal places.",
        "schema_sql": FROGS_SCHEMA, "seed_sql": FROGS_SEED,
        "expected_result": [[69.17]],
        "order_matters": False,
        "hints": [
            "This needs AVG on the score column — and rounding, since averages get messy.",
            "ROUND(AVG(column), 2) keeps the average to 2 decimal places.",
            "SELECT ROUND(AVG(score), 2) FROM frogs;",
        ],
        "xp_reward": 150, "coin_reward": 35, "skill_unlocked": "AVG",
    },
    {
        "id": "w2_l04", "order": 18, "world": 2,
        "title": "Lightest and Heaviest",
        "story": "Two frogs are about to compete for \"Lightest Leaper\" and \"Heavyweight Champion\" — the judges need the exact numbers.",
        "concept_title": "MIN and MAX",
        "concept_explanation": "MIN(column) and MAX(column) return the smallest and largest values — you can ask for both in one query.",
        "example": {"query": "SELECT MIN(id), MAX(id) FROM pond_visitors;", "columns": ["MIN(id)", "MAX(id)"], "result": [[1, 2]]},
        "mission": "Find the lightest weight and the heaviest weight among all frogs, in that order.",
        "schema_sql": FROGS_SCHEMA, "seed_sql": FROGS_SEED,
        "expected_result": [[4.5, 20.0]],
        "order_matters": False,
        "hints": [
            "You need two aggregates in the same SELECT.",
            "MIN(weight_kg), MAX(weight_kg) — separate them with a comma.",
            "SELECT MIN(weight_kg), MAX(weight_kg) FROM frogs;",
        ],
        "xp_reward": 160, "coin_reward": 35, "skill_unlocked": "MIN / MAX",
    },
    {
        "id": "w2_l05", "order": 19, "world": 2,
        "title": "Team Headcounts",
        "story": "Four racing teams are forming for the village games. The organizer needs a headcount per team.",
        "concept_title": "GROUP BY — One Row Per Group",
        "concept_explanation": "GROUP BY column collapses rows sharing the same value into one group, so an aggregate like COUNT(*) is computed per group instead of for the whole table.",
        "example": {"query": "SELECT day, COUNT(*) FROM pond_visitors GROUP BY day;", "columns": ["day", "COUNT(*)"], "result": [["Monday", 1], ["Tuesday", 1]]},
        "mission": "Count how many frogs are on each team, sorted alphabetically by team name.",
        "schema_sql": FROGS_SCHEMA, "seed_sql": FROGS_SEED,
        "expected_result": [["Croak", 3], ["Hop", 3], ["Leap", 3], ["Splash", 3]],
        "order_matters": True,
        "hints": [
            "You need a count, but split out per team, not one grand total.",
            "GROUP BY team splits the frogs into per-team groups before counting.",
            "SELECT team, COUNT(*) FROM frogs GROUP BY team ORDER BY team;",
        ],
        "xp_reward": 170, "coin_reward": 40, "skill_unlocked": "GROUP BY",
    },
    {
        "id": "w2_l06", "order": 20, "world": 2,
        "title": "Color-Coded Weigh-In",
        "story": "The village vet weighs frogs by color group for the yearly health report.",
        "concept_title": "GROUP BY + AVG Together",
        "concept_explanation": "Any aggregate can follow a GROUP BY — AVG per group works exactly like COUNT per group did.",
        "example": None,
        "mission": "Find the average weight for each color, rounded to 2 decimal places, sorted alphabetically by color.",
        "schema_sql": FROGS_SCHEMA, "seed_sql": FROGS_SEED,
        "expected_result": [["blue", 7.23], ["brown", 13.75], ["green", 9.43], ["red", 15.5], ["yellow", 4.5]],
        "order_matters": True,
        "hints": [
            "Group by color first, then average the weight within each group.",
            "SELECT color, ROUND(AVG(weight_kg), 2) FROM frogs GROUP BY color — don't forget to sort.",
            "SELECT color, ROUND(AVG(weight_kg), 2) FROM frogs GROUP BY color ORDER BY color;",
        ],
        "xp_reward": 170, "coin_reward": 40, "skill_unlocked": "GROUP BY + AVG",
    },
    {
        "id": "w2_l07", "order": 21, "world": 2,
        "title": "The Popular Teams Filter",
        "story": "Only teams with more than 2 members get their own tent at the village games.",
        "concept_title": "HAVING — Filter After Grouping",
        "concept_explanation": "WHERE filters rows before grouping; HAVING filters GROUPS after aggregation — you can't write WHERE COUNT(*) > 2, but HAVING COUNT(*) > 2 works.",
        "example": None,
        "mission": "Find every team with more than 2 members, sorted alphabetically.",
        "schema_sql": FROGS_SCHEMA, "seed_sql": FROGS_SEED,
        "expected_result": [["Croak", 3], ["Hop", 3], ["Leap", 3], ["Splash", 3]],
        "order_matters": True,
        "hints": [
            "You're filtering on the group's count, which WHERE can't do.",
            "HAVING comes after GROUP BY and filters the grouped results.",
            "SELECT team, COUNT(*) FROM frogs GROUP BY team HAVING COUNT(*) > 2 ORDER BY team;",
        ],
        "xp_reward": 180, "coin_reward": 40, "skill_unlocked": "HAVING",
    },
    {
        "id": "w2_l08", "order": 22, "world": 2,
        "title": "The Village Elder's Challenge",
        "story": "The village elder wants proof you've mastered aggregates: \"Show me every color whose average score beats 70, best average first.\"",
        "concept_title": "Mini-Boss: GROUP BY + HAVING + ORDER BY",
        "concept_explanation": "No new skill — combine everything from this world in one query.",
        "example": None,
        "mission": "Find every color with an average score above 70 (rounded to 2 decimals), sorted from highest average to lowest.",
        "schema_sql": FROGS_SCHEMA, "seed_sql": FROGS_SEED,
        "expected_result": [["blue", 87.0], ["yellow", 82.0], ["green", 73.0]],
        "order_matters": True,
        "hints": [
            "Group by color, then filter the groups by their average score.",
            "HAVING AVG(score) > 70 filters groups; ORDER BY the same average, descending.",
            "SELECT color, ROUND(AVG(score), 2) AS avg_score FROM frogs GROUP BY color HAVING AVG(score) > 70 ORDER BY avg_score DESC;",
        ],
        "xp_reward": 280, "coin_reward": 65, "skill_unlocked": "World 2 Complete",
    },
]

WORLD_3_LEVELS = [
    {
        "id": "w3_l01", "order": 23, "world": 3,
        "title": "Crossing to the Islands",
        "story": "Beyond the meadow, the frogs have settled into four named ponds scattered like islands. Each frog belongs to (at most) one pond — and the ponds have their own table now.",
        "concept_title": "INNER JOIN — Combine Two Tables",
        "concept_explanation": "INNER JOIN combines rows from two tables where a condition matches — table1 JOIN table2 ON table1.key = table2.key keeps only rows that match on both sides.",
        "example": None,
        "mission": "List every frog's name next to the name of the pond it lives in.",
        "schema_sql": VILLAGE_SCHEMA, "seed_sql": VILLAGE_SEED,
        "expected_result": [
            ["Bullfrog", "Frost Pond"], ["Hoppy", "Mangrove Pond"], ["Kermit", "Willow Pond"], ["Krok", "Mangrove Pond"],
            ["Marsh", "Willow Pond"], ["Michigan", "Frost Pond"], ["Pepe", "Willow Pond"], ["Rana", "Frost Pond"],
            ["Ribbit", "Mangrove Pond"], ["Splash", "Willow Pond"],
        ],
        "order_matters": True,
        "hints": [
            "You need columns from BOTH the frogs table and the ponds table — that's a join.",
            "frogs.pond_id matches ponds.id — that's the join condition.",
            "SELECT frogs.name, ponds.name FROM frogs INNER JOIN ponds ON frogs.pond_id = ponds.id ORDER BY frogs.name;",
        ],
        "xp_reward": 180, "coin_reward": 40, "skill_unlocked": "INNER JOIN",
    },
    {
        "id": "w3_l02", "order": 24, "world": 3,
        "title": "Short Names for Long Tables",
        "story": "Typing \"frogs\" and \"ponds\" over and over gets old fast — the village scribes use shorthand instead.",
        "concept_title": "Table Aliases",
        "concept_explanation": "FROM frogs f JOIN ponds p ON ... gives each table a short alias (f, p) you can use everywhere else in the query instead of the full name.",
        "example": None,
        "mission": "Using aliases f and p, list the name of every frog living in a tropical-climate pond, along with the pond's name.",
        "schema_sql": VILLAGE_SCHEMA, "seed_sql": VILLAGE_SEED,
        "expected_result": [["Hoppy", "Mangrove Pond"], ["Krok", "Mangrove Pond"], ["Ribbit", "Mangrove Pond"]],
        "order_matters": True,
        "hints": [
            "Alias frogs as f and ponds as p, then join and filter by climate.",
            "f JOIN p ON f.pond_id = p.id WHERE p.climate = 'tropical'",
            "SELECT f.name, p.name FROM frogs f JOIN ponds p ON f.pond_id = p.id WHERE p.climate = 'tropical' ORDER BY f.name;",
        ],
        "xp_reward": 180, "coin_reward": 40, "skill_unlocked": "Aliases",
    },
    {
        "id": "w3_l03", "order": 25, "world": 3,
        "title": "The Homeless Frogs",
        "story": "A couple of young frogs haven't picked a pond yet — INNER JOIN would hide them entirely, since they have nothing to match.",
        "concept_title": "LEFT JOIN — Keep Everything on the Left",
        "concept_explanation": "LEFT JOIN keeps every row from the left table, even ones with no match on the right — unmatched columns come back empty. WHERE right_table.id IS NULL finds exactly the unmatched rows.",
        "example": None,
        "mission": "Find every frog that has no pond assigned yet.",
        "schema_sql": VILLAGE_SCHEMA, "seed_sql": VILLAGE_SEED,
        "expected_result": [["Lily"], ["Toady"]],
        "order_matters": False,
        "hints": [
            "INNER JOIN would hide these frogs entirely — you need LEFT JOIN instead.",
            "LEFT JOIN keeps unmatched frogs too, with a NULL pond — filter for that NULL.",
            "SELECT f.name FROM frogs f LEFT JOIN ponds p ON f.pond_id = p.id WHERE p.id IS NULL ORDER BY f.name;",
        ],
        "xp_reward": 190, "coin_reward": 45, "skill_unlocked": "LEFT JOIN",
    },
    {
        "id": "w3_l04", "order": 26, "world": 3,
        "title": "The Empty Oasis",
        "story": "Desert Oasis was built for frogs who love the heat — but not a single frog has moved in.",
        "concept_title": "LEFT JOIN the Other Direction",
        "concept_explanation": (
            "LEFT JOIN isn't just for the \"many\" side — start FROM ponds this time to find ponds with no matching frogs. "
            "(This is also what a RIGHT JOIN frogs on the other side would give you — RIGHT JOIN is just LEFT JOIN with the tables swapped.)"
        ),
        "example": None,
        "mission": "Find every pond that currently has no frogs living in it.",
        "schema_sql": VILLAGE_SCHEMA, "seed_sql": VILLAGE_SEED,
        "expected_result": [["Desert Oasis"]],
        "order_matters": False,
        "hints": [
            "This time start from ponds and LEFT JOIN frogs onto it.",
            "A pond with no frogs will have a NULL frog id after the join.",
            "SELECT p.name FROM ponds p LEFT JOIN frogs f ON f.pond_id = p.id WHERE f.id IS NULL;",
        ],
        "xp_reward": 190, "coin_reward": 45, "skill_unlocked": "LEFT JOIN (reversed)",
    },
    {
        "id": "w3_l05", "order": 27, "world": 3,
        "title": "Every Pond's Population",
        "story": "The village census now needs every pond listed — including the empty one — with how many frogs live there.",
        "concept_title": "LEFT JOIN + GROUP BY",
        "concept_explanation": "Combining LEFT JOIN with GROUP BY counts even the groups with zero matches, unlike an INNER JOIN which would drop them.",
        "example": None,
        "mission": "List every pond's name with how many frogs live there, sorted alphabetically by pond name (Desert Oasis should show 0).",
        "schema_sql": VILLAGE_SCHEMA, "seed_sql": VILLAGE_SEED,
        "expected_result": [["Desert Oasis", 0], ["Frost Pond", 3], ["Mangrove Pond", 3], ["Willow Pond", 4]],
        "order_matters": True,
        "hints": [
            "Start from ponds so the empty one isn't dropped, then LEFT JOIN frogs.",
            "COUNT(f.id) counts only real frog rows, not the NULL placeholder for an empty pond.",
            "SELECT p.name, COUNT(f.id) FROM ponds p LEFT JOIN frogs f ON f.pond_id = p.id GROUP BY p.name ORDER BY p.name;",
        ],
        "xp_reward": 200, "coin_reward": 45, "skill_unlocked": "LEFT JOIN + GROUP BY",
    },
    {
        "id": "w3_l06", "order": 28, "world": 3,
        "title": "The Island Guardian",
        "story": "A guardian blocks the bridge onward: \"Show me every star performer and which island they call home — best score first.\"",
        "concept_title": "Mini-Boss: JOIN + WHERE + ORDER BY",
        "concept_explanation": "No new skill — combine a join with filtering and sorting, exactly like you've done separately.",
        "example": None,
        "mission": "List the name and pond of every frog scoring above 70, best score first.",
        "schema_sql": VILLAGE_SCHEMA, "seed_sql": VILLAGE_SEED,
        "expected_result": [
            ["Splash", "Willow Pond"], ["Kermit", "Willow Pond"], ["Ribbit", "Mangrove Pond"],
            ["Marsh", "Willow Pond"], ["Pepe", "Willow Pond"],
        ],
        "order_matters": True,
        "hints": [
            "Join frogs to ponds, then filter by score, then sort.",
            "WHERE f.score > 70 filters after the join; ORDER BY f.score DESC sorts by score.",
            "SELECT f.name, p.name FROM frogs f JOIN ponds p ON f.pond_id = p.id WHERE f.score > 70 ORDER BY f.score DESC;",
        ],
        "xp_reward": 300, "coin_reward": 70, "skill_unlocked": "World 3 Complete",
    },
]

WORLD_4_LEVELS = [
    {
        "id": "w4_l01", "order": 29, "world": 4,
        "title": "Into the Mystery Forest",
        "story": "A fog-covered forest hides frogs who only reveal themselves to those who can ask a question about a question.",
        "concept_title": "Subqueries — A Query Inside a Query",
        "concept_explanation": "A subquery in parentheses runs first and its result feeds into the outer query — like WHERE column > (SELECT AVG(column) FROM table).",
        "example": None,
        "mission": "Find every frog heavier than the village's average weight.",
        "schema_sql": VILLAGE_SCHEMA, "seed_sql": VILLAGE_SEED,
        "expected_result": [["Bullfrog"], ["Hoppy"], ["Krok"], ["Michigan"], ["Toady"]],
        "order_matters": False,
        "hints": [
            "You need the average weight first, then compare each frog to it.",
            "(SELECT AVG(weight_kg) FROM frogs) computed inline is the subquery.",
            "SELECT name FROM frogs WHERE weight_kg > (SELECT AVG(weight_kg) FROM frogs) ORDER BY name;",
        ],
        "xp_reward": 200, "coin_reward": 45, "skill_unlocked": "Subqueries",
    },
    {
        "id": "w4_l02", "order": 30, "world": 4,
        "title": "The Frost-Loving Frogs",
        "story": "The forest spirit only trusts frogs from ponds cold enough to keep secrets.",
        "concept_title": "Subquery with IN",
        "concept_explanation": "WHERE column IN (subquery) checks a column against a whole list a subquery produces.",
        "example": None,
        "mission": "Find every frog living in a pond whose climate is 'cold'.",
        "schema_sql": VILLAGE_SCHEMA, "seed_sql": VILLAGE_SEED,
        "expected_result": [["Bullfrog"], ["Michigan"], ["Rana"]],
        "order_matters": False,
        "hints": [
            "First find the cold ponds' ids, then find frogs living in one of them.",
            "WHERE pond_id IN (SELECT id FROM ponds WHERE climate = 'cold')",
            "SELECT name FROM frogs WHERE pond_id IN (SELECT id FROM ponds WHERE climate = 'cold') ORDER BY name;",
        ],
        "xp_reward": 200, "coin_reward": 45, "skill_unlocked": "Subquery + IN",
    },
    {
        "id": "w4_l03", "order": 31, "world": 4,
        "title": "The Weight Class Sign",
        "story": "A wooden sign at the forest edge sorts every visitor into a weight class before letting them pass.",
        "concept_title": "CASE — Conditional Labels",
        "concept_explanation": "CASE WHEN cond1 THEN 'a' WHEN cond2 THEN 'b' ELSE 'c' END picks a value per row based on conditions, checked top to bottom.",
        "example": None,
        "mission": "Label every frog's weight class: under 8kg is 'Light', under 13kg is 'Medium', otherwise 'Heavy'.",
        "schema_sql": VILLAGE_SCHEMA, "seed_sql": VILLAGE_SEED,
        "expected_result": [
            ["Bullfrog", "Heavy"], ["Hoppy", "Medium"], ["Kermit", "Medium"], ["Krok", "Heavy"], ["Lily", "Light"],
            ["Marsh", "Medium"], ["Michigan", "Medium"], ["Pepe", "Light"], ["Rana", "Medium"], ["Ribbit", "Light"],
            ["Splash", "Light"], ["Toady", "Heavy"],
        ],
        "order_matters": True,
        "hints": [
            "This needs a CASE expression checked against weight_kg, in order.",
            "CASE WHEN weight_kg < 8 THEN 'Light' WHEN weight_kg < 13 THEN 'Medium' ELSE 'Heavy' END",
            "SELECT name, CASE WHEN weight_kg < 8 THEN 'Light' WHEN weight_kg < 13 THEN 'Medium' ELSE 'Heavy' END FROM frogs ORDER BY name;",
        ],
        "xp_reward": 210, "coin_reward": 50, "skill_unlocked": "CASE",
    },
    {
        "id": "w4_l04", "order": 32, "world": 4,
        "title": "Filling in the Blanks",
        "story": "The forest's roll call refuses to leave any frog's home blank — homeless frogs get marked \"No Pond Yet\" instead.",
        "concept_title": "COALESCE — A Fallback for Missing Values",
        "concept_explanation": "COALESCE(column, 'fallback') returns the column's value, or the fallback if the column is NULL.",
        "example": None,
        "mission": "List every frog's name and its pond name — frogs with no pond should show 'No Pond Yet' instead of a blank.",
        "schema_sql": VILLAGE_SCHEMA, "seed_sql": VILLAGE_SEED,
        "expected_result": [
            ["Bullfrog", "Frost Pond"], ["Hoppy", "Mangrove Pond"], ["Kermit", "Willow Pond"], ["Krok", "Mangrove Pond"],
            ["Lily", "No Pond Yet"], ["Marsh", "Willow Pond"], ["Michigan", "Frost Pond"], ["Pepe", "Willow Pond"],
            ["Rana", "Frost Pond"], ["Ribbit", "Mangrove Pond"], ["Splash", "Willow Pond"], ["Toady", "No Pond Yet"],
        ],
        "order_matters": True,
        "hints": [
            "LEFT JOIN first, so homeless frogs stay in the result with a NULL pond name.",
            "Wrap the pond name in COALESCE(p.name, 'No Pond Yet') to replace the NULL.",
            "SELECT f.name, COALESCE(p.name, 'No Pond Yet') FROM frogs f LEFT JOIN ponds p ON f.pond_id = p.id ORDER BY f.name;",
        ],
        "xp_reward": 210, "coin_reward": 50, "skill_unlocked": "COALESCE",
    },
    {
        "id": "w4_l05", "order": 33, "world": 4,
        "title": "Proof of Life",
        "story": "The forest spirit wants proof: which ponds actually have at least one frog living there?",
        "concept_title": "EXISTS — Does a Match Exist?",
        "concept_explanation": "WHERE EXISTS (subquery) is true if the subquery returns at least one row — it doesn't care what the row contains, only that it exists.",
        "example": None,
        "mission": "Find every pond that has at least one frog living in it.",
        "schema_sql": VILLAGE_SCHEMA, "seed_sql": VILLAGE_SEED,
        "expected_result": [["Frost Pond"], ["Mangrove Pond"], ["Willow Pond"]],
        "order_matters": False,
        "hints": [
            "For each pond, check whether any frog references it.",
            "EXISTS (SELECT 1 FROM frogs f WHERE f.pond_id = p.id) checks for a match.",
            "SELECT name FROM ponds p WHERE EXISTS (SELECT 1 FROM frogs f WHERE f.pond_id = p.id) ORDER BY name;",
        ],
        "xp_reward": 220, "coin_reward": 50, "skill_unlocked": "EXISTS",
    },
    {
        "id": "w4_l06", "order": 34, "world": 4,
        "title": "The Silent Oasis, Revisited",
        "story": "This time the forest spirit wants the opposite proof: which pond has never had a single visitor?",
        "concept_title": "NOT EXISTS",
        "concept_explanation": "NOT EXISTS flips EXISTS — true only when the subquery finds nothing at all.",
        "example": None,
        "mission": "Find every pond that has no frogs living in it, using NOT EXISTS.",
        "schema_sql": VILLAGE_SCHEMA, "seed_sql": VILLAGE_SEED,
        "expected_result": [["Desert Oasis"]],
        "order_matters": False,
        "hints": [
            "This is the mirror image of the last mission.",
            "NOT EXISTS (SELECT 1 FROM frogs f WHERE f.pond_id = p.id) means no frog matched.",
            "SELECT name FROM ponds p WHERE NOT EXISTS (SELECT 1 FROM frogs f WHERE f.pond_id = p.id);",
        ],
        "xp_reward": 220, "coin_reward": 50, "skill_unlocked": "NOT EXISTS",
    },
    {
        "id": "w4_l07", "order": 35, "world": 4,
        "title": "Two Guest Lists, One Party",
        "story": "The forest festival invites two different groups of frogs — the guest list should have each name only once, even if a frog qualifies both ways.",
        "concept_title": "UNION — Combine Result Sets",
        "concept_explanation": "UNION stacks the results of two SELECTs into one list and removes duplicates (UNION ALL would keep them).",
        "example": None,
        "mission": "List the name of every green frog, together with the name of every frog on the Hop team — each name should appear only once.",
        "schema_sql": VILLAGE_SCHEMA, "seed_sql": VILLAGE_SEED,
        "expected_result": [["Hoppy"], ["Kermit"], ["Krok"], ["Pepe"], ["Rana"], ["Toady"]],
        "order_matters": True,
        "hints": [
            "Write two separate SELECTs, one per condition, and combine them.",
            "UNION between two SELECTs merges the lists and drops duplicates automatically.",
            "SELECT name FROM frogs WHERE color = 'green' UNION SELECT name FROM frogs WHERE team = 'Hop' ORDER BY name;",
        ],
        "xp_reward": 220, "coin_reward": 55, "skill_unlocked": "UNION",
    },
    {
        "id": "w4_l08", "order": 36, "world": 4,
        "title": "The Forest Spirit's Riddle",
        "story": "\"Tell me,\" says the forest spirit, \"for every frog: where do they live — or 'Wandering' if nowhere — and are they a Star (score 80+) or a Rookie?\"",
        "concept_title": "Mini-Boss: CASE + COALESCE Together",
        "concept_explanation": "No new skill — combine a LEFT JOIN, COALESCE, and CASE in one query.",
        "example": None,
        "mission": "For every frog, show its name, its pond name (or 'Wandering' if it has none), and 'Star' if its score is 80 or above, else 'Rookie'.",
        "schema_sql": VILLAGE_SCHEMA, "seed_sql": VILLAGE_SEED,
        "expected_result": [
            ["Bullfrog", "Frost Pond", "Rookie"], ["Hoppy", "Mangrove Pond", "Rookie"], ["Kermit", "Willow Pond", "Star"],
            ["Krok", "Mangrove Pond", "Rookie"], ["Lily", "Wandering", "Star"], ["Marsh", "Willow Pond", "Rookie"],
            ["Michigan", "Frost Pond", "Rookie"], ["Pepe", "Willow Pond", "Rookie"], ["Rana", "Frost Pond", "Rookie"],
            ["Ribbit", "Mangrove Pond", "Star"], ["Splash", "Willow Pond", "Star"], ["Toady", "Wandering", "Rookie"],
        ],
        "order_matters": True,
        "hints": [
            "LEFT JOIN for the pond, COALESCE for the fallback name, CASE for the star/rookie label.",
            "COALESCE(p.name, 'Wandering') and CASE WHEN f.score >= 80 THEN 'Star' ELSE 'Rookie' END, side by side.",
            "SELECT f.name, COALESCE(p.name, 'Wandering') AS home, CASE WHEN f.score >= 80 THEN 'Star' ELSE 'Rookie' END AS rank FROM frogs f LEFT JOIN ponds p ON f.pond_id = p.id ORDER BY f.name;",
        ],
        "xp_reward": 320, "coin_reward": 75, "skill_unlocked": "World 4 Complete",
    },
]

WORLD_5_LEVELS = [
    {
        "id": "w5_l01", "order": 37, "world": 5,
        "title": "Entering Wizard Forest",
        "story": "A wizened old toad teaches a trick for naming a subquery so you can reuse it, instead of repeating it everywhere.",
        "concept_title": "WITH — Common Table Expressions",
        "concept_explanation": "WITH name AS (SELECT ...) defines a temporary named result you can SELECT from afterward, like giving a subquery its own label.",
        "example": None,
        "mission": "Using a CTE named heavy_frogs for frogs over 10kg, list just their names.",
        "schema_sql": VILLAGE_SCHEMA, "seed_sql": VILLAGE_SEED,
        "expected_result": [["Bullfrog"], ["Hoppy"], ["Krok"], ["Michigan"], ["Toady"]],
        "order_matters": False,
        "hints": [
            "Define the CTE first with WITH, then SELECT from it like a table.",
            "WITH heavy_frogs AS (SELECT name, weight_kg FROM frogs WHERE weight_kg > 10) SELECT name FROM heavy_frogs;",
            "WITH heavy_frogs AS (SELECT name, weight_kg FROM frogs WHERE weight_kg > 10) SELECT name FROM heavy_frogs ORDER BY name;",
        ],
        "xp_reward": 220, "coin_reward": 50, "skill_unlocked": "WITH / CTE",
    },
    {
        "id": "w5_l02", "order": 38, "world": 5,
        "title": "The Wizard's Ledger",
        "story": "The wizard keeps a ledger of pond populations — but only cares about the popular ones, 3 residents or more.",
        "concept_title": "CTE with Aggregation",
        "concept_explanation": "A CTE can contain a GROUP BY just like any query — then you join or filter the CTE's output afterward.",
        "example": None,
        "mission": "Using a CTE that counts frogs per pond_id, list the pond name and count for every pond with 3 or more frogs, sorted by pond name.",
        "schema_sql": VILLAGE_SCHEMA, "seed_sql": VILLAGE_SEED,
        "expected_result": [["Frost Pond", 3], ["Mangrove Pond", 3], ["Willow Pond", 4]],
        "order_matters": True,
        "hints": [
            "Build the per-pond counts in the CTE, then join it back to ponds for names.",
            "WITH pond_counts AS (SELECT pond_id, COUNT(*) AS n FROM frogs WHERE pond_id IS NOT NULL GROUP BY pond_id) ...",
            "WITH pond_counts AS (SELECT pond_id, COUNT(*) AS n FROM frogs WHERE pond_id IS NOT NULL GROUP BY pond_id) SELECT p.name, pc.n FROM pond_counts pc JOIN ponds p ON p.id = pc.pond_id WHERE pc.n >= 3 ORDER BY p.name;",
        ],
        "xp_reward": 230, "coin_reward": 55, "skill_unlocked": "CTE + Aggregation",
    },
    {
        "id": "w5_l03", "order": 39, "world": 5,
        "title": "The Warm Ponds Registry",
        "story": "The wizard's apprentice is compiling a registry of everyone living somewhere tropical.",
        "concept_title": "CTE Feeding a Join",
        "concept_explanation": "A CTE can be joined to a real table exactly like any other table.",
        "example": None,
        "mission": "Using a CTE of tropical ponds, list every frog's name living in one, with the pond's name.",
        "schema_sql": VILLAGE_SCHEMA, "seed_sql": VILLAGE_SEED,
        "expected_result": [["Hoppy", "Mangrove Pond"], ["Krok", "Mangrove Pond"], ["Ribbit", "Mangrove Pond"]],
        "order_matters": True,
        "hints": [
            "Define the tropical ponds as a CTE first, then join frogs to it.",
            "WITH tropical_ponds AS (SELECT id, name FROM ponds WHERE climate = 'tropical') ...",
            "WITH tropical_ponds AS (SELECT id, name FROM ponds WHERE climate = 'tropical') SELECT f.name, tp.name FROM frogs f JOIN tropical_ponds tp ON f.pond_id = tp.id ORDER BY f.name;",
        ],
        "xp_reward": 230, "coin_reward": 55, "skill_unlocked": "CTE + JOIN",
    },
    {
        "id": "w5_l04", "order": 40, "world": 5,
        "title": "The Recursive Spell",
        "story": "The wizard casts a spell that keeps calling itself, counting down from five to one — a CTE that references itself.",
        "concept_title": "Recursive CTEs",
        "concept_explanation": "WITH RECURSIVE name(col) AS (base_case UNION ALL recursive_case) builds a result step by step, where the recursive part refers back to the CTE itself, stopping once its WHERE condition fails.",
        "example": None,
        "mission": "Using a recursive CTE, count down from 5 to 1.",
        "schema_sql": VILLAGE_SCHEMA, "seed_sql": VILLAGE_SEED,
        "expected_result": [[5], [4], [3], [2], [1]],
        "order_matters": True,
        "hints": [
            "Start the CTE at 5, then keep subtracting 1 until you reach 1.",
            "WITH RECURSIVE countdown(n) AS (SELECT 5 UNION ALL SELECT n - 1 FROM countdown WHERE n > 1) SELECT n FROM countdown;",
            "WITH RECURSIVE countdown(n) AS (SELECT 5 UNION ALL SELECT n - 1 FROM countdown WHERE n > 1) SELECT n FROM countdown;",
        ],
        "xp_reward": 240, "coin_reward": 60, "skill_unlocked": "Recursive CTE",
    },
    {
        "id": "w5_l05", "order": 41, "world": 5,
        "title": "The Wizard's Final Lesson",
        "story": "\"One last lesson,\" the wizard says. \"Build me a CTE of every frog scoring 70 or above, then show me just their names, best score first.\"",
        "concept_title": "Mini-Boss: CTE + ORDER BY",
        "concept_explanation": "No new skill — a CTE feeding a simple sorted SELECT, exactly like you've done with a plain subquery before.",
        "example": None,
        "mission": "Using a CTE of frogs scoring 70 or above, list their names, best score first.",
        "schema_sql": VILLAGE_SCHEMA, "seed_sql": VILLAGE_SEED,
        "expected_result": [["Splash"], ["Kermit"], ["Ribbit"], ["Lily"], ["Marsh"], ["Pepe"], ["Hoppy"]],
        "order_matters": True,
        "hints": [
            "Keep score in the CTE so you can still sort by it afterward.",
            "WITH scored AS (SELECT name, score FROM frogs WHERE score >= 70) SELECT name FROM scored ORDER BY score DESC;",
            "WITH scored AS (SELECT name, score FROM frogs WHERE score >= 70) SELECT name FROM scored ORDER BY score DESC;",
        ],
        "xp_reward": 340, "coin_reward": 80, "skill_unlocked": "World 5 Complete",
    },
]

WORLD_6_LEVELS = [
    {
        "id": "w6_l01", "order": 42, "world": 6,
        "title": "The Volcano's Leaderboard",
        "story": "At the foot of a rumbling volcano, a leaderboard etches itself into stone — rank 1 for the best score, and onward.",
        "concept_title": "ROW_NUMBER() OVER — Number the Rows",
        "concept_explanation": "ROW_NUMBER() OVER (ORDER BY column DESC) numbers every row 1, 2, 3... in that sorted order, without collapsing rows like GROUP BY would.",
        "example": None,
        "mission": "Number every frog 1st, 2nd, 3rd... by score, highest first, showing name, score, and rank.",
        "schema_sql": VILLAGE_SCHEMA, "seed_sql": VILLAGE_SEED,
        "expected_result": [
            ["Splash", 95, 1], ["Kermit", 92, 2], ["Ribbit", 88, 3], ["Lily", 82, 4], ["Marsh", 78, 5], ["Pepe", 75, 6],
            ["Hoppy", 70, 7], ["Krok", 65, 8], ["Rana", 60, 9], ["Michigan", 55, 10], ["Toady", 40, 11], ["Bullfrog", 30, 12],
        ],
        "order_matters": True,
        "hints": [
            "This needs a window function, not GROUP BY — every row stays, just numbered.",
            "ROW_NUMBER() OVER (ORDER BY score DESC) AS rn numbers rows in that sorted order.",
            "SELECT name, score, ROW_NUMBER() OVER (ORDER BY score DESC) AS rn FROM frogs ORDER BY rn;",
        ],
        "xp_reward": 240, "coin_reward": 55, "skill_unlocked": "ROW_NUMBER()",
    },
    {
        "id": "w6_l02", "order": 43, "world": 6,
        "title": "Ties on the Scoreboard",
        "story": "Unlike ROW_NUMBER, this leaderboard gives equal frogs equal rank — no arbitrary tie-breaking.",
        "concept_title": "RANK() OVER — Rank with Ties",
        "concept_explanation": "RANK() gives tied rows the same rank and skips the next number(s) — unlike ROW_NUMBER, which always numbers 1, 2, 3... even for ties.",
        "example": None,
        "mission": "Rank every frog by weight, heaviest first, showing name, weight, and rank (break any tie by name).",
        "schema_sql": VILLAGE_SCHEMA, "seed_sql": VILLAGE_SEED,
        "expected_result": [
            ["Bullfrog", 20.0, 1], ["Toady", 15.5, 2], ["Krok", 13.3, 3], ["Michigan", 12.0, 4], ["Hoppy", 11.0, 5],
            ["Rana", 9.9, 6], ["Marsh", 9.0, 7], ["Kermit", 8.5, 8], ["Ribbit", 7.2, 9], ["Pepe", 6.0, 10],
            ["Splash", 5.5, 11], ["Lily", 4.5, 12],
        ],
        "order_matters": True,
        "hints": [
            "Same idea as ROW_NUMBER, different function name.",
            "RANK() OVER (ORDER BY weight_kg DESC) AS rk",
            "SELECT name, weight_kg, RANK() OVER (ORDER BY weight_kg DESC) AS rk FROM frogs ORDER BY rk, name;",
        ],
        "xp_reward": 240, "coin_reward": 55, "skill_unlocked": "RANK()",
    },
    {
        "id": "w6_l03", "order": 44, "world": 6,
        "title": "Team Champions",
        "story": "Each team wants its own internal ranking — the volcano doesn't care who's best overall, only who's best on each team.",
        "concept_title": "PARTITION BY — Reset Per Group",
        "concept_explanation": "PARTITION BY column restarts the window calculation for each group, like a GROUP BY that doesn't collapse rows — RANK() OVER (PARTITION BY team ORDER BY score DESC) ranks within each team separately.",
        "example": None,
        "mission": "Rank every frog by score within its own team (best score = rank 1 per team), showing name, team, score, and team_rank.",
        "schema_sql": VILLAGE_SCHEMA, "seed_sql": VILLAGE_SEED,
        "expected_result": [
            ["Rana", "Croak", 60, 1], ["Michigan", "Croak", 55, 2], ["Bullfrog", "Croak", 30, 3],
            ["Hoppy", "Hop", 70, 1], ["Krok", "Hop", 65, 2], ["Toady", "Hop", 40, 3],
            ["Kermit", "Leap", 92, 1], ["Ribbit", "Leap", 88, 2], ["Marsh", "Leap", 78, 3],
            ["Splash", "Splash", 95, 1], ["Lily", "Splash", 82, 2], ["Pepe", "Splash", 75, 3],
        ],
        "order_matters": True,
        "hints": [
            "Add PARTITION BY team so the ranking restarts for each team.",
            "RANK() OVER (PARTITION BY team ORDER BY score DESC) AS team_rank",
            "SELECT name, team, score, RANK() OVER (PARTITION BY team ORDER BY score DESC) AS team_rank FROM frogs ORDER BY team, team_rank;",
        ],
        "xp_reward": 250, "coin_reward": 60, "skill_unlocked": "PARTITION BY",
    },
    {
        "id": "w6_l04", "order": 45, "world": 6,
        "title": "One Champion Per Pond",
        "story": "Each pond crowns exactly one champion — the highest scorer living there.",
        "concept_title": "Filtering a Window Function's Result",
        "concept_explanation": "You can't put a window function directly in WHERE — wrap the query in a subquery, then filter the outer query on the window function's alias.",
        "example": None,
        "mission": "Find the top-scoring frog in each pond (frogs with a pond only) — show name, pond_id, and score.",
        "schema_sql": VILLAGE_SCHEMA, "seed_sql": VILLAGE_SEED,
        "expected_result": [["Splash", 1, 95], ["Rana", 2, 60], ["Ribbit", 3, 88]],
        "order_matters": True,
        "hints": [
            "Compute a per-pond rank in a subquery, then filter for rank 1 on the outside.",
            "SELECT ... FROM (SELECT ..., RANK() OVER (PARTITION BY pond_id ORDER BY score DESC) AS rk FROM frogs WHERE pond_id IS NOT NULL) WHERE rk = 1",
            "SELECT name, pond_id, score FROM (SELECT name, pond_id, score, RANK() OVER (PARTITION BY pond_id ORDER BY score DESC) AS rk FROM frogs WHERE pond_id IS NOT NULL) WHERE rk = 1 ORDER BY pond_id;",
        ],
        "xp_reward": 260, "coin_reward": 60, "skill_unlocked": "Window function subquery",
    },
    {
        "id": "w6_l05", "order": 46, "world": 6,
        "title": "Who's Just Behind?",
        "story": "The volcano's oracle wants to know, for every frog on the leaderboard, exactly who scored just above them.",
        "concept_title": "LAG() OVER — Look at the Previous Row",
        "concept_explanation": "LAG(column, 1, default) OVER (ORDER BY ...) reads the value from the previous row in that order — the 3rd argument is what to use when there is no previous row (the very first row).",
        "example": None,
        "mission": "For every frog sorted by score (highest first), show its name, score, and the previous frog's score (use 0 for the very first row).",
        "schema_sql": VILLAGE_SCHEMA, "seed_sql": VILLAGE_SEED,
        "expected_result": [
            ["Splash", 95, 0], ["Kermit", 92, 95], ["Ribbit", 88, 92], ["Lily", 82, 88], ["Marsh", 78, 82], ["Pepe", 75, 78],
            ["Hoppy", 70, 75], ["Krok", 65, 70], ["Rana", 60, 65], ["Michigan", 55, 60], ["Toady", 40, 55], ["Bullfrog", 30, 40],
        ],
        "order_matters": True,
        "hints": [
            "LAG looks backward one row in the given order — use its 3rd argument for the first row's default.",
            "LAG(score, 1, 0) OVER (ORDER BY score DESC) AS prev_score",
            "SELECT name, score, LAG(score, 1, 0) OVER (ORDER BY score DESC) AS prev_score FROM frogs ORDER BY score DESC;",
        ],
        "xp_reward": 260, "coin_reward": 60, "skill_unlocked": "LAG()",
    },
    {
        "id": "w6_l06", "order": 47, "world": 6,
        "title": "The Volcano's Trial",
        "story": "The volcano rumbles one last time: \"Show me the top TWO scorers on every team.\"",
        "concept_title": "Mini-Boss: Top-N Per Group",
        "concept_explanation": "No new skill — combine PARTITION BY with ROW_NUMBER and a filtering subquery, exactly like the champion-per-pond mission.",
        "example": None,
        "mission": "Find the top 2 scoring frogs on each team, showing name, team, and score, sorted by team then score descending.",
        "schema_sql": VILLAGE_SCHEMA, "seed_sql": VILLAGE_SEED,
        "expected_result": [
            ["Rana", "Croak", 60], ["Michigan", "Croak", 55], ["Hoppy", "Hop", 70], ["Krok", "Hop", 65],
            ["Kermit", "Leap", 92], ["Ribbit", "Leap", 88], ["Splash", "Splash", 95], ["Lily", "Splash", 82],
        ],
        "order_matters": True,
        "hints": [
            "Number each team's frogs by score in a subquery, then keep only rn <= 2.",
            "ROW_NUMBER() OVER (PARTITION BY team ORDER BY score DESC) AS rn, then WHERE rn <= 2 outside.",
            "SELECT name, team, score FROM (SELECT name, team, score, ROW_NUMBER() OVER (PARTITION BY team ORDER BY score DESC) AS rn FROM frogs) WHERE rn <= 2 ORDER BY team, score DESC;",
        ],
        "xp_reward": 360, "coin_reward": 85, "skill_unlocked": "World 6 Complete",
    },
]

WORLD_7_LEVELS = [
    {
        "id": "w7_l01", "order": 48, "world": 7,
        "title": "The Kingdom Gates",
        "story": "The gates of the SQL Kingdom finally open. The gatekeeper asks for proof you can bring every skill together, starting with joins and aggregates.",
        "concept_title": "Final Boss: JOIN + GROUP BY + HAVING",
        "concept_explanation": "No new skill — everything from Worlds 3 and 2, combined.",
        "example": None,
        "mission": "For ponds with 3 or more frogs, show the pond name, frog count, and average score (rounded to 2 decimals), best average first.",
        "schema_sql": VILLAGE_SCHEMA, "seed_sql": VILLAGE_SEED,
        "expected_result": [["Willow Pond", 4, 85.0], ["Mangrove Pond", 3, 74.33], ["Frost Pond", 3, 48.33]],
        "order_matters": True,
        "hints": [
            "Join ponds to frogs, group by pond, then filter and sort by the aggregates.",
            "GROUP BY p.name HAVING COUNT(f.id) >= 3 ORDER BY avg_score DESC",
            "SELECT p.name, COUNT(f.id) AS n, ROUND(AVG(f.score), 2) AS avg_score FROM ponds p JOIN frogs f ON f.pond_id = p.id GROUP BY p.name HAVING COUNT(f.id) >= 3 ORDER BY avg_score DESC;",
        ],
        "xp_reward": 280, "coin_reward": 65, "skill_unlocked": "Kingdom Trial I",
    },
    {
        "id": "w7_l02", "order": 49, "world": 7,
        "title": "The Throne Room Puzzle",
        "story": "In the throne room, a puzzle demands the single best frog from every team, using the tools of the Wizard Forest and Volcano Valley together.",
        "concept_title": "Final Boss: CTE + Window Function",
        "concept_explanation": "No new skill — a CTE holding a RANK() calculation, then filtered for the winners.",
        "example": None,
        "mission": "Using a CTE, find the top-scoring frog on each team — show name, team, score, sorted by team.",
        "schema_sql": VILLAGE_SCHEMA, "seed_sql": VILLAGE_SEED,
        "expected_result": [["Rana", "Croak", 60], ["Hoppy", "Hop", 70], ["Kermit", "Leap", 92], ["Splash", "Splash", 95]],
        "order_matters": True,
        "hints": [
            "Build the per-team ranking in a CTE, then select where rank equals 1.",
            "WITH ranked AS (SELECT name, team, score, RANK() OVER (PARTITION BY team ORDER BY score DESC) AS rk FROM frogs) SELECT ... WHERE rk = 1",
            "WITH ranked AS (SELECT name, team, score, RANK() OVER (PARTITION BY team ORDER BY score DESC) AS rk FROM frogs) SELECT name, team, score FROM ranked WHERE rk = 1 ORDER BY team;",
        ],
        "xp_reward": 290, "coin_reward": 70, "skill_unlocked": "Kingdom Trial II",
    },
    {
        "id": "w7_l03", "order": 50, "world": 7,
        "title": "The Scale of Judgment",
        "story": "A final scale weighs every frog's story at once — where they live, and whether they outweigh the village average.",
        "concept_title": "Final Boss: Subquery + LEFT JOIN + CASE",
        "concept_explanation": "No new skill — a scalar subquery inside a CASE, alongside a LEFT JOIN with COALESCE.",
        "example": None,
        "mission": "For every frog, show its name, its pond (or 'Wandering'), and 'Heavyweight' if it's above the village's average weight, else 'Lightweight'.",
        "schema_sql": VILLAGE_SCHEMA, "seed_sql": VILLAGE_SEED,
        "expected_result": [
            ["Bullfrog", "Frost Pond", "Heavyweight"], ["Hoppy", "Mangrove Pond", "Heavyweight"], ["Kermit", "Willow Pond", "Lightweight"],
            ["Krok", "Mangrove Pond", "Heavyweight"], ["Lily", "Wandering", "Lightweight"], ["Marsh", "Willow Pond", "Lightweight"],
            ["Michigan", "Frost Pond", "Heavyweight"], ["Pepe", "Willow Pond", "Lightweight"], ["Rana", "Frost Pond", "Lightweight"],
            ["Ribbit", "Mangrove Pond", "Lightweight"], ["Splash", "Willow Pond", "Lightweight"], ["Toady", "Wandering", "Heavyweight"],
        ],
        "order_matters": True,
        "hints": [
            "LEFT JOIN for the pond, COALESCE for the fallback, and a subquery inside the CASE for the average.",
            "CASE WHEN f.weight_kg > (SELECT AVG(weight_kg) FROM frogs) THEN 'Heavyweight' ELSE 'Lightweight' END",
            "SELECT f.name, COALESCE(p.name, 'Wandering') AS home, CASE WHEN f.weight_kg > (SELECT AVG(weight_kg) FROM frogs) THEN 'Heavyweight' ELSE 'Lightweight' END AS class FROM frogs f LEFT JOIN ponds p ON f.pond_id = p.id ORDER BY f.name;",
        ],
        "xp_reward": 300, "coin_reward": 70, "skill_unlocked": "Kingdom Trial III",
    },
    {
        "id": "w7_l04", "order": 51, "world": 7,
        "title": "The SQL Kingdom's Crown",
        "story": (
            "At last, the Kingdom's crown rests on a final pedestal. The royal frog speaks: "
            "\"Bring me every pond's champion — the single heaviest-scoring frog each pond has ever produced.\""
        ),
        "concept_title": "Final Boss: Correlated Subquery",
        "concept_explanation": "No new skill — a subquery that references the OUTER query's current pond (a correlated subquery), used to find each pond's own maximum.",
        "example": None,
        "mission": "For every pond, find the frog with the highest score living there — show pond name, frog name, and score, sorted by pond name.",
        "schema_sql": VILLAGE_SCHEMA, "seed_sql": VILLAGE_SEED,
        "expected_result": [["Frost Pond", "Rana", 60], ["Mangrove Pond", "Ribbit", 88], ["Willow Pond", "Splash", 95]],
        "order_matters": True,
        "hints": [
            "For each frog, check whether its score equals the MAX score among frogs in the SAME pond.",
            "The inner MAX subquery must filter by the outer pond's id — that's what makes it \"correlated\".",
            "SELECT p.name, f.name, f.score FROM ponds p JOIN frogs f ON f.pond_id = p.id WHERE f.score = (SELECT MAX(f2.score) FROM frogs f2 WHERE f2.pond_id = p.id) ORDER BY p.name;",
        ],
        "xp_reward": 500, "coin_reward": 120, "skill_unlocked": "SQL Kingdom Conquered",
    },
]

GRAND_TRIAL_LEVEL = {
    "id": "grand_trial", "order": 52, "world": 8,
    "title": "The Grand Trial",
    "story": (
        "Every frog you've helped, every pond you've mapped, every skill you've learned — it all leads here. "
        "The Kingdom's council has one final request before naming you a true SQL Master Frog: "
        "prove you can combine everything, one more time, without a map to follow."
    ),
    "concept_title": "The Grand Trial",
    "concept_explanation": (
        "No new syntax — this is a test of everything from Worlds 1-7: joins, aggregates, GROUP BY, HAVING, and rounding, "
        "used together exactly like World 7's final challenges. There's no new concept card here on purpose — "
        "you already know everything you need."
    ),
    "example": None,
    "mission": (
        "For every climate that is home to more than one frog, show the climate, how many frogs live there, "
        "and the average score of those frogs (rounded to 2 decimal places) — sorted from highest average score to lowest."
    ),
    "schema_sql": VILLAGE_SCHEMA, "seed_sql": VILLAGE_SEED,
    "expected_result": [["temperate", 4, 85.0], ["tropical", 3, 74.33], ["cold", 3, 48.33]],
    "order_matters": True,
    "hints": [
        "You'll need to join frogs to ponds, group by the pond's climate, filter by group size, and sort by the average.",
        "GROUP BY p.climate HAVING COUNT(f.id) > 1 ORDER BY avg_score DESC — the rest is the join and the rounded average.",
        "SELECT p.climate, COUNT(f.id) AS frog_count, ROUND(AVG(f.score), 2) AS avg_score FROM ponds p JOIN frogs f ON f.pond_id = p.id GROUP BY p.climate HAVING COUNT(f.id) > 1 ORDER BY avg_score DESC;",
    ],
    "xp_reward": 1000, "coin_reward": 250, "skill_unlocked": "SQL Master Frog",
}

ALL_NEW_LEVELS = (
    WORLD_2_LEVELS + WORLD_3_LEVELS + WORLD_4_LEVELS + WORLD_5_LEVELS
    + WORLD_6_LEVELS + WORLD_7_LEVELS + [GRAND_TRIAL_LEVEL]
)

# Every level from World 3 onward uses the two-table village schema instead
# of the single `frogs` table SqlFrogLevelDetailView's schema panel was
# hardcoded for — this maps each of those level ids to its real multi-table
# reference view instead.
VILLAGE_LEVEL_IDS = {
    lvl["id"] for lvl in (WORLD_3_LEVELS + WORLD_4_LEVELS + WORLD_5_LEVELS + WORLD_6_LEVELS + WORLD_7_LEVELS)
} | {"grand_trial"}

WORLD_NAMES = {
    1: "Beginner Pond",
    2: "Frog Village",
    3: "Connected Islands",
    4: "Mystery Forest",
    5: "Wizard Forest",
    6: "Volcano Valley",
    7: "SQL Kingdom",
    8: "The Grand Trial",
}
