# Generated by Django 5.1.4 on 2026-03-27 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_discussionmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=40)),
                ('language_id', models.PositiveIntegerField()),
                ('source_code', models.TextField()),
                ('stdin', models.TextField(blank=True, default='')),
                ('stdout', models.TextField(blank=True, default='')),
                ('stderr', models.TextField(blank=True, default='')),
                ('compile_output', models.TextField(blank=True, default='')),
                ('status_description', models.CharField(default='Unknown', max_length=120)),
                ('execution_time', models.CharField(blank=True, default='', max_length=40)),
                ('memory', models.CharField(blank=True, default='', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_records', to='learning.problem')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='execution_records', to='learning.studentprofile')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
