# Generated by Django 5.1.4 on 2026-03-27 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_problem_editorial_problem_examples_problem_hints_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='joining_date',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='source_faculty_id',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='status',
        ),
    ]
