# Generated by Django 5.1.4 on 2026-03-28 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_remove_staffprofile_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='campus_rank',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
