# Generated by Django 5.1.4 on 2026-03-30 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0009_alter_studentprofile_campus_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemsolution',
            name='all_tests_passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='problemsolution',
            name='space_complexity',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='problemsolution',
            name='time_complexity',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='problemsolution',
            name='time_spent_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ProblemSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='learning.problem')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_sessions', to='learning.studentprofile')),
            ],
            options={
                'ordering': ('-started_at',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('student', 'problem', 'is_active'), name='unique_active_session_per_student_problem')],
            },
        ),
    ]
