# Generated by Django 5.1.4 on 2026-03-30 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0010_problemsolution_all_tests_passed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolvedProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='JavaScript', max_length=40)),
                ('solved_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solved_by', to='learning.problem')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solved_problems', to='learning.studentprofile')),
            ],
            options={
                'ordering': ('-solved_at',),
                'constraints': [models.UniqueConstraint(fields=('student', 'problem'), name='unique_student_problem_solved')],
            },
        ),
    ]
