# Generated by Django 5.1.4 on 2026-03-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0011_solvedproblem'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='password',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
