# Generated by Django 5.1.4 on 2026-03-30 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0012_staffprofile_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='updated_at',
        ),
    ]
