# Generated by Django 5.1.4 on 2026-03-30 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0014_institution_staffprofile_institution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='role',
            field=models.CharField(choices=[('staff', 'Staff'), ('hod', 'Head of Department'), ('administrator', 'Administrator')], default='staff', max_length=20),
        ),
    ]
