# Generated by Django 5.1.4 on 2026-03-30 18:18

from django.db import migrations


def set_1223_as_hod(apps, schema_editor):
    """Set staff member with faculty_id '1223' as HOD."""
    StaffProfile = apps.get_model('learning', 'StaffProfile')
    
    # Find staff with faculty_id 1223
    staff = StaffProfile.objects.filter(faculty_id='1223').first()
    if staff:
        staff.role = 'hod'
        staff.save(update_fields=['role'])
        print(f"✓ Set {staff.name} (ID: {staff.faculty_id}) as HOD")
    else:
        print("✗ Staff with ID 1223 not found")


def revert_hod_role(apps, schema_editor):
    """Revert HOD role back to staff."""
    StaffProfile = apps.get_model('learning', 'StaffProfile')
    
    staff = StaffProfile.objects.filter(faculty_id='1223').first()
    if staff:
        staff.role = 'staff'
        staff.save(update_fields=['role'])


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0015_add_staff_role'),
    ]

    operations = [
        migrations.RunPython(set_1223_as_hod, revert_hod_role),
    ]
