# Generated by Django 5.1.4 on 2026-04-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0016_set_1223_as_hod'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('class_representative', 'Class Representative'), ('placement_coordinator', 'Placement Coordinator')], default='student', max_length=25),
        ),
    ]
