# Generated by Django 5.1.4 on 2026-04-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0017_studentprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='batch',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
