# Generated by Django 5.1.4 on 2026-04-14 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0022_contest_contestsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether staff can access the system'),
        ),
    ]
