# Generated by Django 5.1.4 on 2026-04-14 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0024_add_batch_to_contest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='assigned_batches',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='assigned_students',
        ),
    ]
