# Generated by Django 5.1.4 on 2026-04-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0025_remove_contest_assigned_batches_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='assigned_batches',
            field=models.JSONField(blank=True, default=list, help_text='List of batch codes assigned to this contest'),
        ),
        migrations.AddField(
            model_name='contest',
            name='assigned_students',
            field=models.ManyToManyField(blank=True, help_text='Specific students assigned to this contest', related_name='assigned_contests', to='learning.studentprofile'),
        ),
    ]
