# Generated by Django 5.1.4 on 2026-04-14 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0026_contest_assigned_batches_contest_assigned_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='HOD who approved this contest', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_contests', to='learning.staffprofile'),
        ),
        migrations.AddField(
            model_name='contest',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='contest',
            name='submitted_for_approval_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('published', 'Published'), ('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
    ]
