# Generated by Django 5.1.4 on 2026-04-14 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0027_contest_approved_at_contest_approved_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('has_started', models.BooleanField(default=True)),
                ('total_score', models.PositiveIntegerField(default=0)),
                ('problems_solved', models.PositiveIntegerField(default=0)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='learning.contest')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_participations', to='learning.studentprofile')),
            ],
            options={
                'db_table': 'contest_participations',
                'ordering': ['-started_at'],
                'constraints': [models.UniqueConstraint(fields=('contest', 'student'), name='unique_contest_student_participation')],
            },
        ),
    ]
