# Generated by Django 5.1.4 on 2026-04-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0028_contestparticipation'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='winners_allocated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contest',
            name='winners_allocated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contestparticipation',
            name='final_rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contestparticipation',
            name='is_winner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contestparticipation',
            name='total_time_taken',
            field=models.PositiveIntegerField(default=0, help_text='Total time taken in seconds'),
        ),
    ]
