# Generated by Django 5.1.4 on 2026-04-20 07:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0029_add_winner_allocation_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_instances', to='learning.problem')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
