# Generated by Django 5.1.4 on 2026-04-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0033_achievement_userachievement'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_maintenance_staff', models.BooleanField(default=False)),
                ('global_maintenance_students', models.BooleanField(default=False)),
                ('global_maintenance_hod', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'system_configurations',
            },
        ),
        migrations.AddField(
            model_name='institution',
            name='database_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='institution',
            name='maintenance_hod',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='institution',
            name='maintenance_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='institution',
            name='maintenance_students',
            field=models.BooleanField(default=False),
        ),
    ]
