# Generated by Django 5.1.4 on 2026-04-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0034_systemconfiguration_institution_database_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='role',
            field=models.CharField(choices=[('staff', 'Staff'), ('hod', 'Head of Department'), ('tpu', 'TPU (Training & Placement)'), ('director', 'Director'), ('admin', 'System Admin')], default='staff', max_length=20),
        ),
    ]
