# Generated by Django 5.1.4 on 2026-04-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0035_alter_staffprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='maintenance_inst_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='institution',
            name='maintenance_ja',
            field=models.BooleanField(default=False),
        ),
    ]
