# Generated by Django 5.1.4 on 2026-04-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0036_institution_maintenance_inst_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='companies',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='role',
            field=models.CharField(choices=[('staff', 'Staff'), ('hod', 'Head of Department'), ('tpu', 'TPU (Training & Placement)'), ('director', 'Director'), ('ja', 'Junior Admin (JA)'), ('admin', 'System Admin')], default='staff', max_length=20),
        ),
    ]
