# Generated by Django 5.1.4 on 2026-04-20 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0037_problem_companies_alter_staffprofile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolvedAptitude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solved_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solved_by', to='learning.aptitudequestion')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solved_aptitude', to='learning.studentprofile')),
            ],
            options={
                'db_table': 'solved_aptitude',
                'ordering': ('-solved_at',),
                'unique_together': {('student', 'question')},
            },
        ),
    ]
