# Generated by Django 5.1.4 on 2026-04-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0038_solvedaptitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='tracked_companies',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
