# Generated by Django 5.1.4 on 2026-04-25 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0039_studentprofile_tracked_companies'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='discussionmessage',
            name='batch_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='discussionmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discussionmessage',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discussionmessage',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discussionmessage',
            name='thread_type',
            field=models.CharField(choices=[('general', 'General Discussion'), ('individual', 'Direct Message'), ('batch', 'Batch Discussion'), ('staff', 'Staff Room'), ('hod_tp_ja', 'HOD / TPU / JA / TPO Panel'), ('problem', 'Problem Specific')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='discussionmessage',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussion_messages', to='learning.studentprofile'),
        ),
    ]
