# Generated by Django 5.1.4 on 2026-04-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0040_discussionmessage_batch_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussionmessage',
            name='is_poll',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discussionmessage',
            name='poll_options',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='discussionmessage',
            name='poll_votes',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
