# Generated by Django 5.1.4 on 2026-04-26 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0041_discussionmessage_is_poll_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussionmessage',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussion_messages', to='learning.department'),
        ),
        migrations.AddField(
            model_name='discussionmessage',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussion_messages', to='learning.institution'),
        ),
    ]
