# Generated by Django 5.1.4 on 2026-04-26 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0042_discussionmessage_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='aptitude_questions',
            field=models.ManyToManyField(blank=True, related_name='contests', to='learning.aptitudequestion'),
        ),
        migrations.AddField(
            model_name='contest',
            name='contest_type',
            field=models.CharField(choices=[('programming', 'Programming'), ('aptitude', 'Aptitude')], default='programming', max_length=20),
        ),
        migrations.CreateModel(
            name='AptitudeContestSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(blank=True, max_length=1, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('score', models.IntegerField(default=0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('time_taken_seconds', models.PositiveIntegerField(default=0)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aptitude_submissions', to='learning.contest')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_submissions', to='learning.aptitudequestion')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aptitude_contest_submissions', to='learning.studentprofile')),
            ],
            options={
                'db_table': 'aptitude_contest_submissions',
                'ordering': ['submitted_at'],
                'unique_together': {('contest', 'student', 'question')},
            },
        ),
    ]
