# Generated by Django 5.1.4 on 2026-04-28 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0043_contest_aptitude_questions_contest_contest_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='category',
            field=models.CharField(choices=[('coding', 'Coding'), ('aptitude', 'Aptitude')], default='coding', max_length=20),
        ),
    ]
