# Generated by Django 5.1.4 on 2026-05-01 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0044_achievement_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='solvedaptitude',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solvedaptitude',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='HOD who approved this aptitude result', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_aptitude_results', to='learning.staffprofile'),
        ),
        migrations.AddField(
            model_name='solvedaptitude',
            name='is_approved_by_hod',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solvedaptitude',
            name='is_visible_to_student',
            field=models.BooleanField(default=False, help_text='Whether student can see this result'),
        ),
    ]
