# Generated by Django 5.1.4 on 2026-05-02 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0045_add_aptitude_approval_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solvedaptitude',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='solvedaptitude',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='solvedaptitude',
            name='is_approved_by_hod',
        ),
        migrations.RemoveField(
            model_name='solvedaptitude',
            name='is_visible_to_student',
        ),
        migrations.AddField(
            model_name='contest',
            name='access_end_time',
            field=models.DateTimeField(blank=True, help_text='When the contest link expires (no new participants allowed)', null=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='access_start_time',
            field=models.DateTimeField(blank=True, help_text='When students can start accessing the contest', null=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='session_duration_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Individual session time limit in minutes (e.g., 30 min from when student starts)'),
        ),
        migrations.AddField(
            model_name='contestparticipation',
            name='auto_submitted',
            field=models.BooleanField(default=False, help_text='True if contest was auto-submitted due to time expiry'),
        ),
        migrations.AddField(
            model_name='contestparticipation',
            name='session_end_time',
            field=models.DateTimeField(blank=True, help_text='When this individual session expires (calculated from started_at + session_duration)', null=True),
        ),
    ]
