# Generated by Django 5.1.4 on 2026-05-02 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0046_add_session_based_contest_timing'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestparticipation',
            name='manually_stopped',
            field=models.BooleanField(default=False, help_text='True if contest was manually stopped by student'),
        ),
    ]
