# Generated by Django 5.1.4 on 2026-05-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0047_add_manually_stopped_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='display_name',
            field=models.CharField(blank=True, default='', help_text='Full display name for reports and headers', max_length=300),
        ),
        migrations.AddField(
            model_name='institution',
            name='established_year',
            field=models.PositiveIntegerField(blank=True, help_text='Year of establishment', null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='logo_url',
            field=models.URLField(blank=True, default='', help_text='URL to college logo image'),
        ),
        migrations.AddField(
            model_name='institution',
            name='subheading',
            field=models.CharField(blank=True, default='', help_text='Subtitle or tagline', max_length=200),
        ),
        migrations.AddField(
            model_name='institution',
            name='website',
            field=models.URLField(blank=True, default='', help_text='Official website URL'),
        ),
    ]
