# Generated by Django 5.1.4 on 2026-05-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0048_add_institution_branding_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='logo_file',
            field=models.ImageField(blank=True, help_text='Uploaded college logo', null=True, upload_to='college_logos/'),
        ),
    ]
