# Generated by Django 5.1.4 on 2026-07-01 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0053_problem_execution_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchadvisor',
            name='advisor',
            field=models.ForeignKey(help_text='Staff member who is the class advisor for this batch/section', on_delete=django.db.models.deletion.CASCADE, related_name='advised_batches', to='learning.staffprofile'),
        ),
        migrations.AlterField(
            model_name='batchadvisor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='execution_type',
            field=models.CharField(choices=[('auto', 'Auto-detect from code'), ('stdin', 'Standard Input / Output'), ('function', 'Function-Based'), ('class', 'Class / Object-Based'), ('interactive', 'Interactive')], default='auto', help_text="How test-case input is passed to the solution. 'auto' detects from code structure.", max_length=20),
        ),
        migrations.AlterField(
            model_name='problem',
            name='function_name',
            field=models.CharField(blank=True, default='', help_text='Explicit function/method name to call. Leave blank to use slug-based detection.', max_length=100),
        ),
    ]
