# Generated by Django 5.1.4 on 2026-07-01 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0054_alter_batchadvisor_advisor_alter_batchadvisor_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Easy', max_length=10)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('examples', models.JSONField(blank=True, default=list)),
                ('hints', models.JSONField(blank=True, default=list)),
                ('editorial', models.TextField(blank=True, default='')),
                ('execution_type', models.CharField(choices=[('auto', 'Auto-detect from code'), ('stdin', 'Standard Input / Output'), ('function', 'Function-Based'), ('class', 'Class / Object-Based'), ('interactive', 'Interactive')], default='auto', max_length=20)),
                ('function_name', models.CharField(blank=True, default='', max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order within the topic')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lab_problems',
                'ordering': ('topic', 'order', 'difficulty', 'title'),
            },
        ),
        migrations.CreateModel(
            name='LabTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(choices=[('array', 'Array'), ('linkedlist', 'Linked List'), ('stack', 'Stack'), ('queue', 'Queue'), ('tree', 'Tree'), ('graph', 'Graph'), ('hash', 'Hash / Map'), ('sort', 'Sorting'), ('search', 'Searching'), ('dp', 'Dynamic Programming'), ('string', 'Strings'), ('recursion', 'Recursion'), ('math', 'Math'), ('other', 'Other')], default='other', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in the grid')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'lab_topics',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='LabSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=40)),
                ('language_id', models.PositiveIntegerField()),
                ('source_code', models.TextField()),
                ('status', models.CharField(default='Attempted', max_length=40)),
                ('passed_cases', models.PositiveIntegerField(default=0)),
                ('total_cases', models.PositiveIntegerField(default=0)),
                ('all_passed', models.BooleanField(default=False)),
                ('execution_time', models.CharField(blank=True, default='', max_length=40)),
                ('memory', models.CharField(blank=True, default='', max_length=40)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='learning.labproblem')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_submissions', to='learning.studentprofile')),
            ],
            options={
                'db_table': 'lab_submissions',
                'ordering': ('-submitted_at',),
            },
        ),
        migrations.CreateModel(
            name='LabTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stdin', models.TextField(blank=True, default='')),
                ('expected_output', models.TextField()),
                ('is_sample', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='learning.labproblem')),
            ],
            options={
                'db_table': 'lab_test_cases',
                'ordering': ('order',),
            },
        ),
        migrations.AddField(
            model_name='labproblem',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='learning.labtopic'),
        ),
    ]
