# Generated by Django 5.1.4 on 2026-07-01 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0055_lab_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'Array Lab – Semester 1'", max_length=200)),
                ('subject', models.CharField(blank=True, default='', max_length=200)),
                ('batch', models.CharField(blank=True, default='', max_length=20)),
                ('year', models.CharField(blank=True, default='', max_length=5)),
                ('section', models.CharField(blank=True, default='', max_length=10)),
                ('deadline', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_staff', models.ForeignKey(blank=True, help_text='Staff who monitors this lab', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_assignments', to='learning.staffprofile')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_lab_assignments', to='learning.staffprofile')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_assignments', to='learning.department')),
                ('lab_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='learning.labtopic')),
            ],
            options={
                'db_table': 'lab_assignments',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='LabAssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=40)),
                ('language_id', models.PositiveIntegerField(default=71)),
                ('source_code', models.TextField()),
                ('output', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='Attempted', max_length=40)),
                ('passed_cases', models.PositiveIntegerField(default=0)),
                ('total_cases', models.PositiveIntegerField(default=0)),
                ('all_passed', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='learning.labassignment')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to='learning.labproblem')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_assignment_submissions', to='learning.studentprofile')),
            ],
            options={
                'db_table': 'lab_assignment_submissions',
                'ordering': ('-updated_at',),
                'constraints': [models.UniqueConstraint(fields=('assignment', 'student', 'problem'), name='unique_lab_assignment_student_problem')],
            },
        ),
    ]
