# Generated by Django 5.1.4 on 2026-07-11 10:32

import apps.learning.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0058_lab_v2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'companies',
                'ordering': ('name',),
            },
        ),
        migrations.RemoveConstraint(
            model_name='labexercisesubmission',
            name='unique_exercise_student',
        ),
        migrations.AddField(
            model_name='lab',
            name='allowed_languages',
            field=models.JSONField(default=apps.learning.models.default_lab_languages),
        ),
        migrations.AddField(
            model_name='lab',
            name='lab_type',
            field=models.CharField(choices=[('practical', 'Lab Practical'), ('company', 'Company Based Lab Practical')], default='practical', max_length=20),
        ),
        migrations.AlterField(
            model_name='labassignment',
            name='deadline',
            field=models.DateTimeField(help_text='When the lab closes (end date)'),
        ),
        migrations.AlterUniqueTogether(
            name='labexercisesubmission',
            unique_together={('exercise', 'student')},
        ),
        migrations.AddField(
            model_name='company',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_companies', to='learning.staffprofile'),
        ),
        migrations.AddField(
            model_name='company',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='learning.department'),
        ),
        migrations.AddField(
            model_name='lab',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labs', to='learning.company'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(fields=('department', 'name'), name='unique_company_per_department'),
        ),
    ]
