# Generated by Django 5.1.4 on 2026-07-11 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0059_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='company',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab', to='learning.company'),
        ),
    ]
