# Generated by Django 5.1.4 on 2026-07-11 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0060_alter_lab_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabExerciseTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stdin', models.TextField(blank=True, default='')),
                ('expected_output', models.TextField()),
                ('is_sample', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='learning.labexercise')),
            ],
            options={
                'db_table': 'lab_exercise_test_cases',
                'ordering': ('order',),
            },
        ),
    ]
