# Generated by Django 5.1.4 on 2026-07-17 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0061_labexercisetestcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='assigned_sections',
            field=models.JSONField(blank=True, default=list, help_text="List of 'batch::section' strings scoping this contest to specific sections within a batch"),
        ),
    ]
