# Generated by Django 5.1.4 on 2026-07-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0062_contest_assigned_sections'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Short label, e.g. 'DeepSeek V4 Pro (NVIDIA)'", max_length=80, unique=True)),
                ('base_url', models.CharField(help_text='OpenAI-compatible base URL, e.g. https://integrate.api.nvidia.com/v1', max_length=255)),
                ('api_key', models.CharField(max_length=255)),
                ('model_name', models.CharField(max_length=120)),
                ('priority', models.PositiveIntegerField(default=0, help_text='Lower tries first')),
                ('is_active', models.BooleanField(default=True)),
                ('use_streaming', models.BooleanField(default=False, help_text='Whether this endpoint requires stream=True (SSE) responses')),
                ('temperature', models.FloatField(default=0.4)),
                ('top_p', models.FloatField(default=0.95)),
                ('max_tokens', models.PositiveIntegerField(default=16384)),
                ('timeout_seconds', models.PositiveIntegerField(default=45)),
                ('extra_body', models.JSONField(blank=True, default=dict, help_text='Provider-specific request extras, e.g. {"chat_template_kwargs": {"thinking": false}}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'llm_providers',
                'ordering': ('priority', 'id'),
            },
        ),
    ]
