# Generated by Django 5.1.4 on 2026-07-19 15:53

from django.conf import settings
from django.db import migrations


def seed_providers(apps, schema_editor):
    LLMProvider = apps.get_model("learning", "LLMProvider")

    seed_1 = getattr(settings, "LLM_PROVIDER_SEED_1", {})
    seed_2 = getattr(settings, "LLM_PROVIDER_SEED_2", {})

    if seed_1.get("api_key"):
        LLMProvider.objects.get_or_create(
            name="DeepSeek V4 Pro (NVIDIA)",
            defaults=dict(
                base_url=seed_1["base_url"],
                api_key=seed_1["api_key"],
                model_name=seed_1["model_name"],
                priority=0,
                is_active=True,
                use_streaming=False,
                temperature=0.4,
                top_p=0.95,
                # Kept well below gunicorn's 120s worker timeout even in the
                # worst case (this provider times out AND the fallback also
                # takes its full timeout) — see timeout_seconds on both rows.
                max_tokens=6000,
                timeout_seconds=seed_1["timeout_seconds"],
                extra_body={"chat_template_kwargs": {"thinking": False}},
            ),
        )

    if seed_2.get("api_key"):
        LLMProvider.objects.get_or_create(
            name="Nemotron 3 Ultra (NVIDIA)",
            defaults=dict(
                base_url=seed_2["base_url"],
                api_key=seed_2["api_key"],
                model_name=seed_2["model_name"],
                priority=10,
                is_active=True,
                use_streaming=True,
                temperature=0.4,
                top_p=0.95,
                max_tokens=6000,
                timeout_seconds=seed_2["timeout_seconds"],
                extra_body={"chat_template_kwargs": {"enable_thinking": True}, "reasoning_budget": 16384},
            ),
        )


def unseed_providers(apps, schema_editor):
    LLMProvider = apps.get_model("learning", "LLMProvider")
    LLMProvider.objects.filter(name__in=["DeepSeek V4 Pro (NVIDIA)", "Nemotron 3 Ultra (NVIDIA)"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0063_llmprovider'),
    ]

    operations = [
        migrations.RunPython(seed_providers, unseed_providers),
    ]
