# Generated by Django 5.1.4 on 2026-07-19 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0064_seed_llm_providers'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabExerciseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_no', models.PositiveIntegerField(default=0)),
                ('exp_name', models.CharField(blank=True, default='', max_length=200)),
                ('aim', models.TextField(blank=True, default='')),
                ('algorithm', models.TextField(blank=True, default='')),
                ('program', models.TextField(blank=True, default='')),
                ('output', models.TextField(blank=True, default='')),
                ('result', models.TextField(blank=True, default='')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='lab_reports/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='learning.labexercisesubmission')),
            ],
            options={
                'db_table': 'lab_exercise_reports',
                'ordering': ('-generated_at',),
            },
        ),
    ]
