# Generated by Django 5.1.4 on 2026-07-19 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0065_labexercisereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmprovider',
            name='last_used_at',
            field=models.DateTimeField(blank=True, help_text='Set automatically each time this provider is picked for a request — drives round-robin selection.', null=True),
        ),
        migrations.AlterField(
            model_name='llmprovider',
            name='priority',
            field=models.PositiveIntegerField(default=0, help_text='Tie-breaker when last_used_at is equal (e.g. never used) — lower goes first'),
        ),
        migrations.AlterField(
            model_name='llmprovider',
            name='use_streaming',
            field=models.BooleanField(default=True, help_text='Whether this endpoint requires stream=True (SSE) responses'),
        ),
    ]
