# Generated by Django 5.1.4 on 2026-07-22 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0066_llmprovider_last_used_at_alter_llmprovider_priority_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AptitudeAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(max_length=1)),
                ('is_correct', models.BooleanField()),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='learning.aptitudequestion')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aptitude_attempts', to='learning.studentprofile')),
            ],
            options={
                'db_table': 'aptitude_attempts',
                'ordering': ('-attempted_at',),
            },
        ),
    ]
