# Generated by Django 5.1.4 on 2026-07-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0068_merge_aptitude_subtopics_into_main_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='labexercise',
            name='explanation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='problem',
            name='explanation',
            field=models.TextField(blank=True, default=''),
        ),
    ]
