# Generated by Django 5.1.4 on 2026-07-24 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0069_add_problem_and_lab_exercise_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='maintenance_director',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='institution',
            name='maintenance_tpu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='global_maintenance_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='global_maintenance_director',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='global_maintenance_ja',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='global_maintenance_tpu',
            field=models.BooleanField(default=False),
        ),
    ]
