# Generated by Django 5.1.4 on 2026-07-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0070_add_all_role_maintenance_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='enable_copy_paste_lock',
            field=models.BooleanField(default=False, help_text='Disable copy and paste in contest workspace'),
        ),
        migrations.AddField(
            model_name='contest',
            name='enable_fullscreen_lock',
            field=models.BooleanField(default=False, help_text='Enforce fullscreen mode during contest'),
        ),
        migrations.AddField(
            model_name='contest',
            name='enable_tab_switch_check',
            field=models.BooleanField(default=True, help_text='Monitor tab switches and window blur during contest'),
        ),
        migrations.AddField(
            model_name='contest',
            name='max_tab_switches',
            field=models.PositiveIntegerField(default=3, help_text='Maximum tab switch warnings before auto-submission'),
        ),
    ]
