# Generated by Django 5.1.4 on 2026-07-24 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0071_contest_enable_copy_paste_lock_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labexercisereport',
            options={},
        ),
        migrations.AddField(
            model_name='lab',
            name='approval_status',
            field=models.CharField(default='approved', max_length=20),
        ),
        migrations.AddField(
            model_name='lab',
            name='enable_copy_paste_lock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lab',
            name='enable_fullscreen_lock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lab',
            name='enable_tab_switch_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lab',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lab',
            name='max_tab_switches',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='lab',
            name='lab_type',
            field=models.CharField(choices=[('practical', 'Lab Practical'), ('company', 'Company Based Lab Practical'), ('university', 'University Lab Practical')], default='practical', max_length=20),
        ),
        migrations.AlterModelTable(
            name='labexercisereport',
            table=None,
        ),
        migrations.CreateModel(
            name='LabStudentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_locked', models.BooleanField(default=False)),
                ('tab_switch_count', models.IntegerField(default=0)),
                ('lock_reason', models.CharField(blank=True, default='', max_length=255)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_sessions', to='learning.lab')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_sessions', to='learning.studentprofile')),
            ],
            options={
                'db_table': 'lab_student_sessions',
                'unique_together': {('lab', 'student')},
            },
        ),
    ]
