# Generated by Django 5.1.4 on 2026-07-26 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0072_alter_labexercisereport_options_lab_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='linked_lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='university_labs', to='learning.lab'),
        ),
        migrations.AddField(
            model_name='labexercise',
            name='difficulty',
            field=models.CharField(default='Medium', max_length=20),
        ),
        migrations.AddField(
            model_name='labstudentsession',
            name='allocated_exercises',
            field=models.ManyToManyField(blank=True, related_name='allocated_sessions', to='learning.labexercise'),
        ),
    ]
