# Generated by Django 5.1.4 on 2026-07-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0073_lab_linked_lab_labexercise_difficulty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestparticipation',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='True if contest workspace is locked due to violation limits'),
        ),
        migrations.AddField(
            model_name='contestparticipation',
            name='lock_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='contestparticipation',
            name='snapshots',
            field=models.JSONField(blank=True, default=list, help_text='List of webcam snapshots captured during proctoring'),
        ),
    ]
