# Generated by Django 5.1.4 on 2026-07-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0074_contestparticipation_is_locked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='allow_copy_paste',
            field=models.BooleanField(default=False, help_text='Allow copy/paste and drag-drop in coding workspace for this student'),
        ),
    ]
