# Generated by Django 5.1.4 on 2026-07-30 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0075_studentprofile_allow_copy_paste'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('version', models.CharField(blank=True, default='', max_length=50)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('feature', 'New Feature'), ('bugfix', 'Improvement & Fix'), ('announcement', 'Announcement')], default='feature', max_length=30)),
                ('target_role', models.CharField(choices=[('all', 'All Roles'), ('student', 'Students Only'), ('staff', 'Faculty Only'), ('hod', 'HODs Only'), ('ja', 'Junior Admins Only'), ('tpu', 'TPU Officers Only'), ('director', 'Directors Only')], default='all', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
