# Generated by Django 5.1.4 on 2026-07-31 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0077_seed_llm_provider_mantle'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='param_schema',
            field=models.JSONField(blank=True, default=None, help_text='Optional structured parameter/return-type schema, e.g. {"params":[{"name":"nums","type":"int[]","order":0},{"name":"target","type":"int","order":1}],"return_type":"int[]"}. Types are limited to int/float/double/string/boolean and their [] / [][] array forms (see services/param_types.py). When null, execution uses the existing regex/heuristic path unchanged — this field is strictly opt-in per problem.', null=True),
        ),
        migrations.AddField(
            model_name='testcase',
            name='input_data',
            field=models.JSONField(blank=True, default=None, help_text='Structured input keyed by the parent Problem.param_schema\'s param names, e.g. {"nums": [2,7,11,15], "target": 9}. Only consulted when the parent Problem has a param_schema; otherwise stdin (unchanged) is used.', null=True),
        ),
    ]
