# Generated by Django on 2026-08-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0078_problem_param_schema_testcase_input_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='labstudentsession',
            name='sub_batch',
            field=models.CharField(blank=True, default='Batch 1', max_length=50),
        ),
    ]
