# Generated by Django 5.1.4 on 2026-08-31 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0079_labstudentsession_sub_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='aptitudequestion',
            name='option_a_image',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='aptitudequestion',
            name='option_b_image',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='aptitudequestion',
            name='option_c_image',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='aptitudequestion',
            name='option_d_image',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='aptitudequestion',
            name='question_image',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='aptitudequestion',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice')], default='MCQ', max_length=20),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='role',
            field=models.CharField(choices=[('staff', 'Staff'), ('hod', 'Head of Department'), ('academics', 'Academic Coordinator'), ('tpu', 'TPU (Training & Placement)'), ('director', 'Director'), ('ja', 'Junior Admin (JA)'), ('admin', 'System Admin')], default='staff', max_length=20),
        ),
    ]
