# Generated by Django 5.1.4 on 2026-08-31 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0080_aptitudequestion_option_a_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingPassage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('passage_text', models.TextField()),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='aptitudequestion',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice'), ('RC', 'Reading Comprehension')], default='MCQ', max_length=20),
        ),
        migrations.AlterField(
            model_name='aptitudequestion',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='learning.aptitudetopic'),
        ),
        migrations.AddField(
            model_name='aptitudequestion',
            name='passage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='learning.readingpassage'),
        ),
    ]
