# Generated by Django 5.1.4 on 2026-08-31 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0081_readingpassage_alter_aptitudequestion_question_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingpassage',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reading_passages', to='learning.aptitudetopic'),
        ),
    ]
