# Generated by Django 5.1.4 on 2026-09-01 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0082_readingpassage_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='enable_webcam_proctoring',
            field=models.BooleanField(default=False, help_text='Require webcam access and capture periodic snapshots during contest'),
        ),
    ]
