# Generated by Django 5.1.4 on 2026-09-01 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0083_contest_enable_webcam_proctoring'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='pass_threshold_percent',
            field=models.PositiveIntegerField(default=70, help_text="Minimum percentage of an exercise's test cases that must pass for a student's submission to be accepted"),
        ),
    ]
