# Generated by Django 5.1.4 on 2026-09-01 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0084_lab_pass_threshold_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='labexercisesubmission',
            name='passed_cases',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='labexercisesubmission',
            name='test_results',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='labexercisesubmission',
            name='total_cases',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
