# Generated by Django 5.1.4 on 2026-09-01 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0085_labexercisesubmission_passed_cases_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='aptitude_weight_percent',
            field=models.PositiveIntegerField(default=33),
        ),
        migrations.AddField(
            model_name='contest',
            name='coding_weight_percent',
            field=models.PositiveIntegerField(default=34),
        ),
        migrations.AddField(
            model_name='contest',
            name='reading_weight_percent',
            field=models.PositiveIntegerField(default=33),
        ),
        migrations.AlterField(
            model_name='contest',
            name='contest_type',
            field=models.CharField(choices=[('programming', 'Programming'), ('aptitude', 'Aptitude'), ('combined', 'Combined (Coding + Aptitude + Reading)')], default='programming', max_length=20),
        ),
    ]
