# Generated by Django 5.1.4 on 2026-09-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0086_contest_aptitude_weight_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='locked_modules',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
