# Generated by Django 5.1.4 on 2026-09-01 12:51

from django.db import migrations, models


INDIVIDUAL_INTERVIEW_TRACKS = {
    "CIVIL": "civil",
    "MECH": "mech",
    "EEE": "eee",
    "ECE": "ece",
}
DEFAULT_COMMON_INTERVIEW_TRACK = "cs_common"


def backfill_interview_tracks(apps, schema_editor):
    Department = apps.get_model('learning', 'Department')
    for dept in Department.objects.all():
        key = (dept.name or "").strip().upper().replace(" ", "")
        dept.interview_track = INDIVIDUAL_INTERVIEW_TRACKS.get(key, DEFAULT_COMMON_INTERVIEW_TRACK)
        dept.save(update_fields=['interview_track'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0087_institution_locked_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='interview_track',
            field=models.CharField(blank=True, default='', help_text='Interview Practice grouping key — departments sharing the same value share one question bank. Defaults by branch, admin-editable.', max_length=40),
        ),
        migrations.RunPython(backfill_interview_tracks, noop_reverse),
    ]
