# Generated by Django 5.1.4 on 2026-09-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0088_department_interview_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
