# Generated by Django 5.1.4 on 2026-09-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0089_staff_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='mobile_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
