# Generated by Django 5.1.4 on 2026-09-01 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0090_staff_profile_mobile_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'examinations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SyllabusSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('order', models.PositiveIntegerField(default=0)),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='learning.examination')),
            ],
            options={
                'db_table': 'syllabus_sections',
                'ordering': ['order', 'id'],
                'unique_together': {('examination', 'title')},
            },
        ),
        migrations.CreateModel(
            name='SyllabusTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('resource_links', models.JSONField(blank=True, default=list)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='learning.syllabussection')),
            ],
            options={
                'db_table': 'syllabus_topics',
                'ordering': ['order', 'id'],
                'unique_together': {('section', 'title')},
            },
        ),
        migrations.CreateModel(
            name='SyllabusSubtopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='learning.syllabustopic')),
            ],
            options={
                'db_table': 'syllabus_subtopics',
                'ordering': ['order', 'id'],
                'unique_together': {('topic', 'title')},
            },
        ),
    ]
