# Generated by Django 5.1.4 on 2026-09-02 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0091_examination_syllabus'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabussubtopic',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='syllabussubtopic',
            name='resource_links',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
