# Generated by Django 5.1.4 on 2026-09-02 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0092_syllabus_subtopic_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitiveQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_image', models.URLField(blank=True, default='')),
                ('video_url', models.URLField(blank=True, default='', help_text='Optional YouTube/video explainer for this question')),
                ('option_a', models.CharField(max_length=500)),
                ('option_b', models.CharField(max_length=500)),
                ('option_c', models.CharField(max_length=500)),
                ('option_d', models.CharField(max_length=500)),
                ('correct_option', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('explanation', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subtopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='learning.syllabussubtopic')),
            ],
            options={
                'db_table': 'competitive_questions',
                'ordering': ['order', 'id'],
            },
        ),
    ]
