# Generated by Django 5.1.4 on 2026-09-02 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0093_competitive_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionUsageMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aptitude_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage_marks', to='learning.aptitudequestion')),
                ('problem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage_marks', to='learning.problem')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_usage_marks', to='learning.staffprofile')),
            ],
            options={
                'db_table': 'question_usage_marks',
                'constraints': [models.UniqueConstraint(condition=models.Q(('aptitude_question__isnull', False)), fields=('staff', 'batch', 'aptitude_question'), name='unique_staff_batch_aptitude_mark'), models.UniqueConstraint(condition=models.Q(('problem__isnull', False)), fields=('staff', 'batch', 'problem'), name='unique_staff_batch_problem_mark')],
            },
        ),
    ]
