# Generated by Django 5.1.4 on 2026-09-03 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0096_backfill_question_usage_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contests', to='learning.staffprofile'),
        ),
    ]
