# Generated by Django 5.1.4 on 2026-09-04 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0097_contest_created_by_set_null'),
    ]

    operations = [
        migrations.CreateModel(
            name='AptitudeExplanationAuditRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('stopped', 'Stopped'), ('completed', 'Completed')], default='idle', max_length=20)),
                ('last_question_id', models.IntegerField(default=0, help_text='Cursor — resume processing questions with id > this')),
                ('processed_count', models.IntegerField(default=0)),
                ('corrected_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('stop_requested', models.BooleanField(default=False)),
                ('last_error', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'aptitude_explanation_audit_runs',
            },
        ),
    ]
