# Generated by Django 5.1.4 on 2026-09-04 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0098_aptitude_explanation_audit_run'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyllabusFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, default='')),
                ('resource_links', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subtopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='learning.syllabussubtopic')),
            ],
            options={
                'db_table': 'syllabus_folders',
                'ordering': ['order', 'id'],
                'unique_together': {('subtopic', 'title')},
            },
        ),
        migrations.AddField(
            model_name='competitivequestion',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='learning.syllabusfolder'),
        ),
        migrations.CreateModel(
            name='SyllabusFolderMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='syllabus_folder_media/')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('content_type', models.CharField(blank=True, default='', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='learning.syllabusfolder')),
            ],
            options={
                'db_table': 'syllabus_folder_media',
                'ordering': ['order', 'id'],
            },
        ),
    ]
