# Generated by Django 5.1.4 on 2026-09-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0099_syllabus_folders'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemMetadataGenerationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('stopped', 'Stopped'), ('completed', 'Completed')], default='idle', max_length=20)),
                ('last_problem_id', models.IntegerField(default=0, help_text='Cursor — resume processing problems with id > this')),
                ('processed_count', models.IntegerField(default=0)),
                ('schema_generated_count', models.IntegerField(default=0)),
                ('explanation_generated_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('stop_requested', models.BooleanField(default=False)),
                ('last_error', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'problem_metadata_generation_runs',
            },
        ),
    ]
