# Generated by Django 5.1.4 on 2026-09-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0100_problem_metadata_generation_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemmetadatagenerationrun',
            name='hints_generated_count',
            field=models.IntegerField(default=0),
        ),
    ]
