# Generated by Django 5.1.4 on 2026-09-04 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0101_problemmetadatagenerationrun_hints_generated_count'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='syllabusfolder',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='syllabusfolder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='learning.syllabusfolder'),
        ),
    ]
