# Generated by Django 5.1.4 on 2026-09-04 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0102_alter_syllabusfolder_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'interview_topics',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InterviewTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'interview_tracks',
            },
        ),
        migrations.CreateModel(
            name='InterviewFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='learning.interviewfolder')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='learning.interviewtopic')),
            ],
            options={
                'db_table': 'interview_folders',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, default='', help_text='Source id, e.g. "CYB-0001" — display only, not a DB key.', max_length=30)),
                ('question_type', models.CharField(choices=[('conceptual', 'Conceptual'), ('technical', 'Technical'), ('scenario', 'Scenario-Based'), ('tool', 'Tool-Based'), ('troubleshooting', 'Troubleshooting'), ('comparison', 'Comparison'), ('process', 'Process / Procedure'), ('behavioral', 'Behavioral / Experience')], default='conceptual', max_length=20)),
                ('difficulty', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=20)),
                ('question_text', models.TextField()),
                ('answer', models.TextField()),
                ('follow_up_question', models.TextField(blank=True, default='')),
                ('follow_up_answer', models.TextField(blank=True, default='')),
                ('tools_technologies', models.CharField(blank=True, default='', max_length=500)),
                ('key_concepts', models.CharField(blank=True, default='', max_length=500)),
                ('source_reference', models.CharField(blank=True, default='', max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='learning.interviewfolder')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='learning.interviewtopic')),
            ],
            options={
                'db_table': 'interview_questions',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='interviewtopic',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='learning.interviewtrack'),
        ),
        migrations.AlterUniqueTogether(
            name='interviewtopic',
            unique_together={('track', 'title')},
        ),
    ]
