# Generated by Django 5.1.4 on 2026-09-04 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0103_interviewtopic_interviewtrack_interviewfolder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewFolderMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='interview_folder_media/')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('content_type', models.CharField(blank=True, default='', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='learning.interviewfolder')),
            ],
            options={
                'db_table': 'interview_folder_media',
                'ordering': ['order', 'id'],
            },
        ),
    ]
