# Generated by Django 5.1.4 on 2026-09-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0105_seed_default_interview_tracks'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewfoldermedia',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='syllabusfoldermedia',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
