# Generated by Django 5.1.4 on 2026-09-05 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0106_folder_media_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SqlFrogProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp', models.PositiveIntegerField(default=0)),
                ('coins', models.PositiveIntegerField(default=0)),
                ('completed_level_ids', models.JSONField(blank=True, default=list)),
                ('hints_used', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sql_frog_progress', to='learning.studentprofile')),
            ],
            options={
                'db_table': 'sql_frog_progress',
            },
        ),
    ]
