# Generated by Django 5.1.4 on 2026-09-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0107_sqlfrogprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='generic_schema',
            field=models.JSONField(blank=True, default=None, help_text='Schema for the generic judge, e.g. {"function_name":"twoSum","params":[["nums","vector<int>"],["target","int"]],"return_type":"vector<int>","custom_structs":{}}. Only read when uses_generic_judge=True. See services/judging/README.md for the full type vocabulary.', null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='memory_limit_kb',
            field=models.IntegerField(blank=True, default=None, help_text="Per-submission Judge0 memory_limit override (KB). Null keeps Judge0's own default.", null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='time_limit_seconds',
            field=models.FloatField(blank=True, default=None, help_text="Per-submission Judge0 cpu_time_limit override. Null keeps Judge0's own default.", null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='uses_generic_judge',
            field=models.BooleanField(default=False, help_text='Opt-in flag for the new type-driven judging framework (services/judging/). False (the default) keeps every existing problem on the unchanged legacy execution path — this field is never set by any migration, only by an author choosing it.'),
        ),
    ]
