# Generated by Django 5.1.4 on 2026-09-05 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0108_problem_generic_schema_problem_memory_limit_kb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmprovider',
            name='input_cost_per_million',
            field=models.DecimalField(decimal_places=4, default=0, help_text='USD per 1,000,000 prompt/input tokens — used to estimate cost on the LLM usage dashboard. Leave 0 if unknown/free.', max_digits=10),
        ),
        migrations.AddField(
            model_name='llmprovider',
            name='output_cost_per_million',
            field=models.DecimalField(decimal_places=4, default=0, help_text='USD per 1,000,000 completion/output tokens — used to estimate cost on the LLM usage dashboard. Leave 0 if unknown/free.', max_digits=10),
        ),
        migrations.CreateModel(
            name='LLMUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=80)),
                ('model_name', models.CharField(blank=True, default='', max_length=120)),
                ('feature', models.CharField(blank=True, default='', help_text="Short tag parsed from the call's log label, e.g. 'generic schema', 'explanation', 'test cases'", max_length=80)),
                ('label', models.CharField(blank=True, default='', help_text='Full log label passed by the caller, e.g. the problem title', max_length=255)),
                ('success', models.BooleanField(default=True)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('estimated_cost', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_logs', to='learning.llmprovider')),
            ],
            options={
                'db_table': 'llm_usage_logs',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['provider_name', 'created_at'], name='llm_usage_l_provide_65a23e_idx'), models.Index(fields=['feature', 'created_at'], name='llm_usage_l_feature_149539_idx')],
            },
        ),
    ]
