# Generated by Django 5.1.4 on 2026-09-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0109_llmprovider_input_cost_per_million_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='explanation_is_story',
            field=models.BooleanField(default=False, help_text="Whether `explanation` was generated with the story-hook prompt (vs. the older plain pedagogical style). Lets the 'Regenerate All Explanations' admin sweep track real DB-persisted progress and skip already-migrated problems on a later run, instead of relying on a browser-held cursor that resets on refresh."),
        ),
    ]
