# Generated by Django 5.1.4 on 2026-09-05 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0110_problem_explanation_is_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='generic_schema_needs_review',
            field=models.BooleanField(default=False, help_text="Set by the 'Validate & Enable Judge' bulk sweep when a schema is still invalid even after one LLM regeneration attempt. Excludes the problem from that sweep's automatic retries (so a handful of permanently-stuck problems can't stall the whole bank-wide pass) until a staff member explicitly retries it — either via the 'Retry Flagged Schemas' bulk action or by fixing/regenerating it individually. Cleared automatically the moment the problem's schema validates successfully."),
        ),
    ]
