# Generated by Django 5.1.4 on 2026-09-05 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0111_problem_generic_schema_needs_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='input_format',
            field=models.CharField(choices=[('wire', 'Wire format (ready to execute)'), ('raw_text', 'Raw example text (needs adapting before execution)')], default='wire', help_text='Explicit, authoritative declaration of what `stdin` actually contains — \'wire\' (services/judging/serializer.py\'s one-value-per-line format, or the legacy driver\'s own JSON-array format; either way, ready to execute as-is) or \'raw_text\' (human-authored LeetCode-style text like \'s = "a", t = "b"\', which every execution path must adapt first — see services/judging/integration.py\'s _effective_stdin()). Exists because \'stored in the DB\' used to silently imply \'already wire format\', which was false for rows created by services/problem_testcases.py\'s sync_problem_test_cases() — this field replaces that guess with a real declaration set at creation time.', max_length=16),
        ),
    ]
