# Generated by Django 5.1.4 on 2026-09-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0112_testcase_input_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='description_is_scenario',
            field=models.BooleanField(default=False, help_text="Whether `description` has been rewritten into a real-world scenario (same input/output contract, no LeetCode branding or cross-references) by the 'Generate Scenario Descriptions' admin sweep. Same DB-persisted-progress convention as explanation_is_story — a problem is only ever rewritten once, and a later sweep click only touches problems still on the original statement."),
        ),
        migrations.AddField(
            model_name='problem',
            name='description_original',
            field=models.TextField(blank=True, default='', help_text='The raw, pre-migration `description` text (usually the original LeetCode-style statement), captured once the first time description_is_scenario flips to True — never overwritten again. Kept so a scenario rewrite can be compared against or reverted from without re-scraping the dataset.'),
        ),
    ]
