# Generated by Django 5.1.4 on 2026-09-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0113_problem_description_scenario'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='generic_starter_code',
            field=models.JSONField(blank=True, default=dict, help_text="{language: code} — persisted output of services/judging/starter_code.generate_generic_starter_code(), one entry per language it could actually generate for (a language whose type shape isn't supported yet, e.g. a 2D array in C, simply has no key here). Populated by the 'Generate Starter Code' admin sweep rather than computed fresh on every API request, so what a student is shown is a stable, admin-reviewable snapshot — hand-editing this field (e.g. to add a missing import) sticks until the sweep is deliberately re-run with force=true. Empty ({}) means 'not generated yet' — ProblemDetailSerializer falls back to generating on the fly in that case, same result, just not cached."),
        ),
    ]
