# Generated by Django 5.1.4 on 2026-09-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0114_problem_generic_starter_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqlfrogprogress',
            name='equipped_cosmetics',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sqlfrogprogress',
            name='owned_cosmetic_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
