# Generated by Django 5.1.4 on 2026-09-08 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0115_sqlfrogprogress_cosmetics'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewQuestionProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('review_again', 'Review Again'), ('learned', 'Learned')], max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='learning.interviewquestion')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_question_progress', to='learning.studentprofile')),
            ],
            options={
                'db_table': 'interview_question_progress',
                'constraints': [models.UniqueConstraint(fields=('student', 'question'), name='unique_interview_question_progress')],
            },
        ),
    ]
