# Generated by Django 5.1.4 on 2026-09-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0116_interviewquestionprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='role',
            field=models.CharField(choices=[('staff', 'Staff'), ('hod', 'Head of Department'), ('academics', 'Academic Coordinator'), ('tpu', 'TPU (Training & Placement)'), ('director', 'Director'), ('principal', 'Principal'), ('ja', 'Junior Admin (JA)'), ('admin', 'System Admin')], default='staff', max_length=20),
        ),
        migrations.AlterField(
            model_name='systemupdate',
            name='target_role',
            field=models.CharField(choices=[('all', 'All Roles'), ('student', 'Students Only'), ('staff', 'Faculty Only'), ('hod', 'HODs Only'), ('ja', 'Junior Admins Only'), ('tpu', 'TPU Officers Only'), ('director', 'Directors Only'), ('principal', 'Principals Only')], default='all', max_length=30),
        ),
    ]
