# Generated by Django 5.1.4 on 2026-09-10 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0117_alter_staffprofile_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='custom_weight_percent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contest',
            name='sections',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='contestparticipation',
            name='section_scores',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='role',
            field=models.CharField(choices=[('staff', 'Staff'), ('hod', 'Head of Department'), ('academics', 'Academic Coordinator'), ('tpu', 'TPU (Training & Placement)'), ('director', 'Director'), ('principal', 'Principal'), ('office_admin', 'Office Admin'), ('ja', 'Junior Admin (JA)'), ('admin', 'System Admin')], default='staff', max_length=20),
        ),
        migrations.AlterField(
            model_name='systemupdate',
            name='target_role',
            field=models.CharField(choices=[('all', 'All Roles'), ('student', 'Students Only'), ('staff', 'Faculty Only'), ('hod', 'HODs Only'), ('ja', 'Junior Admins Only'), ('tpu', 'TPU Officers Only'), ('director', 'Directors Only'), ('principal', 'Principals Only'), ('office_admin', 'Office Admins Only')], default='all', max_length=30),
        ),
        migrations.CreateModel(
            name='ContestCustomQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('question_text', models.TextField()),
                ('question_image', models.URLField(blank=True, default='', max_length=1000)),
                ('option_a', models.CharField(max_length=500)),
                ('option_b', models.CharField(max_length=500)),
                ('option_c', models.CharField(max_length=500)),
                ('option_d', models.CharField(max_length=500)),
                ('correct_option', models.CharField(max_length=1)),
                ('explanation', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_questions', to='learning.contest')),
            ],
            options={
                'db_table': 'contest_custom_questions',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContestCustomAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(blank=True, max_length=1, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('score', models.IntegerField(default=0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('time_taken_seconds', models.PositiveIntegerField(default=0)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_answers', to='learning.contest')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_custom_answers', to='learning.studentprofile')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='learning.contestcustomquestion')),
            ],
            options={
                'db_table': 'contest_custom_answers',
                'ordering': ['submitted_at'],
                'unique_together': {('contest', 'student', 'question')},
            },
        ),
    ]
