# Generated by Django 5.1.4 on 2026-09-10 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0118_contest_custom_weight_percent_contest_sections_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='deletion_denied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='deletion_denied_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='contest',
            name='deletion_request_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='contest',
            name='deletion_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contest',
            name='deletion_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='deletion_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_contest_deletions', to='learning.staffprofile'),
        ),
    ]
