# Generated by Django 5.1.4 on 2026-09-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0119_contest_deletion_denied_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='explanation_is_unified',
            field=models.BooleanField(default=False, help_text="Whether `explanation` was (re)written with the current single continuous 'Problem Explanation' prompt — one flowing piece with no Story Hook/Core Problem Concept/Step-by-Step headings, hook woven in, 1-2 worked samples inline. This is the flag the 'Generate Problem Explanations' admin sweep (AdminProblemBankGenerateEverythingView) tracks progress against — explanation_is_story alone can't tell a problem apart that's still on the old multi-section style, so a problem already migrated to THAT would otherwise be (wrongly) skipped forever."),
        ),
        migrations.AlterField(
            model_name='problem',
            name='explanation_is_story',
            field=models.BooleanField(default=False, help_text="Whether `explanation` was generated with the (now-retired) multi-section story-hook prompt (Story Hook / Core Problem Concept / Step-by-Step Approach headings) rather than the original plain pedagogical style. Superseded by explanation_is_unified for the current single-block 'Problem Explanation' prompt — kept only so old data can still be told apart from the very first (pre-story) style if that's ever needed."),
        ),
    ]
