# Generated by Django 5.1.4 on 2026-09-12 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0120_problem_explanation_is_unified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='assigned_batches',
            field=models.JSONField(blank=True, default=list, help_text='Batch codes this announcement targets — same shape/rules as Contest.assigned_batches. Empty = not batch-restricted.'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='assigned_sections',
            field=models.JSONField(blank=True, default=list, help_text="'batch::section' entries this announcement is restricted to — same shape as Contest.assigned_sections."),
        ),
        migrations.AddField(
            model_name='announcement',
            name='assigned_students',
            field=models.ManyToManyField(blank=True, help_text='Specific students this announcement targets (e.g. a contest assigned to hand-picked individuals). When set, ONLY these students see it, regardless of department/batch/section scoping above.', related_name='individual_announcements', to='learning.studentprofile'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Null = every department in the institution (or fully global if institution is also null).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='learning.department'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='institution',
            field=models.ForeignKey(blank=True, help_text='Null = every institution (system-wide). Set to scope to one institution.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='learning.institution'),
        ),
    ]
