# Generated by Django 5.1.4 on 2026-09-12 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0121_announcement_assigned_batches_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnSprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('sections', models.JSONField(blank=True, default=list)),
                ('programming_per_day', models.PositiveIntegerField(default=0)),
                ('aptitude_per_day', models.PositiveIntegerField(default=0)),
                ('reading_per_day', models.PositiveIntegerField(default=0)),
                ('manual_per_day', models.PositiveIntegerField(default=0)),
                ('topic_config', models.JSONField(blank=True, default=dict)),
                ('daily_start_time', models.TimeField(blank=True, null=True)),
                ('daily_end_time', models.TimeField(blank=True, null=True)),
                ('sprint_dates', models.JSONField(blank=True, default=list)),
                ('batch', models.CharField(max_length=20)),
                ('section', models.CharField(blank=True, default='', max_length=10)),
                ('programming_weight_percent', models.PositiveIntegerField(default=25)),
                ('aptitude_weight_percent', models.PositiveIntegerField(default=25)),
                ('reading_weight_percent', models.PositiveIntegerField(default=25)),
                ('manual_weight_percent', models.PositiveIntegerField(default=25)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('published', 'Published'), ('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('submitted_for_approval_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='HOD who approved this sprint', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_learn_sprints', to='learning.staffprofile')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learn_sprints', to='learning.staffprofile')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learn_sprints', to='learning.department')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learn_sprints', to='learning.institution')),
            ],
            options={
                'db_table': 'learn_sprints',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearnSprintDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('allocated_problem_ids', models.JSONField(blank=True, default=list)),
                ('allocated_aptitude_question_ids', models.JSONField(blank=True, default=list)),
                ('contest', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learnsprintday', to='learning.contest')),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='learning.learnsprint')),
            ],
            options={
                'db_table': 'learn_sprint_days',
                'ordering': ['day_number'],
                'unique_together': {('sprint', 'day_number')},
            },
        ),
        migrations.CreateModel(
            name='LearnSprintManualQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('question_text', models.TextField()),
                ('question_image', models.URLField(blank=True, default='', max_length=1000)),
                ('option_a', models.CharField(max_length=500)),
                ('option_b', models.CharField(max_length=500)),
                ('option_c', models.CharField(max_length=500)),
                ('option_d', models.CharField(max_length=500)),
                ('correct_option', models.CharField(max_length=1)),
                ('explanation', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_questions', to='learning.learnsprintday')),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_questions', to='learning.learnsprint')),
            ],
            options={
                'db_table': 'learn_sprint_manual_questions',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LearnSprintBadgeAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_code', models.CharField(choices=[('champion', 'Sprint Champion'), ('podium', 'Podium Finish'), ('perfect_attendance', 'Perfect Attendance'), ('day_champion', 'Day Champion')], max_length=30)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badge_awards', to='learning.learnsprint')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learn_sprint_badges', to='learning.studentprofile')),
            ],
            options={
                'db_table': 'learn_sprint_badge_awards',
                'ordering': ['-awarded_at'],
                'unique_together': {('sprint', 'student', 'badge_code')},
            },
        ),
    ]
