# Generated by Django 5.1.4 on 2026-09-12 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0122_learnsprint_learnsprintday_learnsprintmanualquestion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PyJourneyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp', models.PositiveIntegerField(default=0)),
                ('coins', models.PositiveIntegerField(default=0)),
                ('completed_level_ids', models.JSONField(blank=True, default=list)),
                ('hints_used', models.JSONField(blank=True, default=dict)),
                ('owned_cosmetic_ids', models.JSONField(blank=True, default=list)),
                ('equipped_cosmetics', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='py_journey_progress', to='learning.studentprofile')),
            ],
            options={
                'db_table': 'py_journey_progress',
            },
        ),
        migrations.CreateModel(
            name='GameBadgeAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_key', models.CharField(max_length=30)),
                ('badge_code', models.CharField(choices=[('first_steps', 'First Steps'), ('world_champion', 'World Champion'), ('game_master', 'Game Master')], max_length=30)),
                ('world', models.PositiveIntegerField(blank=True, null=True)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_badges', to='learning.studentprofile')),
            ],
            options={
                'db_table': 'game_badge_awards',
                'ordering': ['-awarded_at'],
                'unique_together': {('student', 'game_key', 'badge_code', 'world')},
            },
        ),
    ]
