# Generated by Django 5.0.6 on 2026-08-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_sessiondeletionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewhistory',
            name='reasoning',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='reasoning',
            field=models.TextField(blank=True, default=''),
        ),
    ]
