services:
  judge0-server:
    image: judge0/judge0:latest
    container_name: judge0-server
    restart: unless-stopped
    ports:
      - "2358:2358"
    privileged: true
    environment:
      - JUDGE0_HOMEPAGE=https://code2day.ramcoad.com
      - RAILS_MAX_THREADS=40
      - REDIS_URL=redis://code2day-redis:6379
    logging:
      driver: json-file
      options:
        max-size: "100M"
    networks:
      - code2day-shared
    depends_on:
      - judge0-workers

  judge0-workers:
    image: judge0/judge0:latest
    container_name: judge0-workers
    restart: unless-stopped
    privileged: true
    command: ["./scripts/workers"]
    environment:
      - JUDGE0_HOMEPAGE=https://code2day.ramcoad.com
      - RAILS_MAX_THREADS=40
      - REDIS_URL=redis://code2day-redis:6379
    logging:
      driver: json-file
      options:
        max-size: "100M"
    networks:
      - code2day-shared

networks:
  code2day-shared:
    external: true
