FROM node:20-alpine

RUN npm install -g \
    # Data structures & algorithms
    lodash \
    underscore \
    collections \
    heap \
    sorted-array \
    # Math & utilities
    mathjs \
    decimal.js \
    big.js \
    # String utilities
    string

WORKDIR /code
